### ISSUE TITLE
Select app title

### ISSUE THREAD

**Issue by AlexVilla** [dpa99c/phonegap-launch-navigator#102]
is in there a method to personalize the title on the select app dialog?, i don't see any and i need to translate it to spanish

**Comment by dpa99c** [comment]
The `appSelectionDialogHeader` option, as listed in the [Parameters](https://github.com/dpa99c/phonegap-launch-navigator#parameters) section, can be used to customise the dialog title. See [illustrated usage in the example project](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L106.)
