### ISSUE TITLE
Waze crashing on "shutdown - closing waze" and returning to ionic app.

### ISSUE THREAD

**Issue by sam-lex** [dpa99c/phonegap-launch-navigator#103]
Hi, I'm using this plugin with an Ionic project, it's working well so far, however, one issue I'm having is, after I close the navigation (in this case Waze), the app blacks out, and gets stuck in the "shutting down mode", if I try to force close Waze, and return to my app, I can see the button used to call the navigation is still pressed, and entire app is in a frozen state, and soon after without doing anything, Waze opens up once again.

I'm wondering if someone is having this problem as well, or perhaps it has anything to do with **partial wakelock** mentioned by @dpa99c in this thread: [Plugin seems to terminate app process when invoked](https://github.com/dpa99c/phonegap-launch-navigator/issues/6).
There were very few instances in which I was able to close Waze, and return normally to my ionic app without any problems, but 8 out of 10 it gets stuck.

this is the code I used to open up Waze with the destination set:
```javascript
function navigateTo(lat, lng) {
  launchnavigator.isAppAvailable( launchnavigator.APP.WAZE, (isAppAvailable) => {
    let app;
    if ( isAppAvailable )
      app = launchnavigator.APP.WAZE;
    else
      app = launchnavigator.APP.USER_SELECT;
    launchnavigator.navigate([ lat, lng ], { app: app });
  });
}
```

ps.: I'm testing on an Android device, and using the Back button to close Waze after it is launched, closing it should make it return to my app automatically.

**Comment by dpa99c** [comment]
The issue in closing the Waze app has nothing to do with this plugin, which simply [launches the Waze app](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/android/LaunchNavigator.java#L583) using its [documented URL scheme](https://www.waze.com/en-GB/about/dev).

I would suggest connecting the device on which you're encountering this issue via USB so you can monitor the Android log via adb logcat (e.g. in Android Studio). This should give you some error messages which indicate the reason for the crash.
