### ISSUE TITLE
Unable to build on iOS, clang linker command failed

### ISSUE THREAD

**Issue by sumitsoman** [dpa99c/phonegap-launch-navigator#105]
I am unable to build the app on XCode on iOS as the build command fails with the following error:

![error](https://cloud.githubusercontent.com/assets/5772710/19917681/59f39d1e-a0eb-11e6-97c4-b79cecf24ae4.png)

I am able to compile, build and run the basic Cordova project on the simulator, but after adding the plugins I get the above error. I tried renaming the variables `CMEmptyAddress` and `CMEmptyCoord` in the files `CMMapLauncher.m` and `CMMapLauncher.h` but on re-building the same error pops up for the renamed variables. Please help on how this can be resolved.

**Comment by dpa99c** [comment]
Duplicates #92
