### ISSUE TITLE
ERROR: has no exported member ' LaunchNavigatorOptions' 

### ISSUE THREAD

**Issue by TelmoFerreira** [dpa99c/phonegap-launch-navigator#109]
If i import { LaunchNavigator, LaunchNavigatorOptions } 	from 'ionic-native'; 

i receive the following error, does anyone knows why ?

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38

thanks

**Comment by dpa99c** [comment]
See the [Ionic 2 example](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic2Example) in the [example project repo for this plugin](https://github.com/dpa99c/phonegap-launch-navigator-example) which illustrates usage of the plugin via the Ionic Native wrapper - specifically, see [home.ts](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/Ionic2Example/src/pages/home/home.ts).

Bear in mind that the [`LaunchNavigator` Ionic Native wrapper for this plugin](https://github.com/driftyco/ionic-native/blob/master/src/plugins/diagnostic.ts) is under the control of [Ionic Native](https://github.com/driftyco/ionic-native) so any issues related specifically to the wrapper should be raised on the [Ionic Native issues page](https://github.com/driftyco/ionic-native/issues).

If you're encountering issues with the Ionic Native wrapper, you can access the plugin API directly via the `launchnavigator` global namespace as described in the plugin documentation.
