### ISSUE TITLE
Support for Tizen Web App

### ISSUE THREAD

**Issue by sumitsoman** [dpa99c/phonegap-launch-navigator#111]
I have an existing iOS and WP8 Cordova app which I need to run for the Tizen platform. My app uses this plugin for showing navigation directions from the current location to a specified location. This is my relevant .js code fragment:

     launchnavigator.navigate(
       [myLat, myLong],
      null,
      function () {
          alert("Starting Navigation!");
      },
      function (error) {
          alert("Error!\n Unable to start navigation: " + error);
      });

But when I debug the Tizen app on my device, the console gives the message:

    ReferenceError: Can't find variable: launchnavigator 

Is this plugin supported for Tizen platform, or could you direct me to a suitable alternative for showing navigation directions?

**Comment by dpa99c** [comment]
As stated at the top of the documentation:

> This Cordova/Phonegap plugin can be used to navigate to a destination by launching native navigation apps on Android, iOS and Windows Phone.

i.e. not Tizen

**Comment by sumitsoman** [comment]
Is there an alternative to do this on Tizen?

**Comment by dpa99c** [comment]
No idea
