### ISSUE TITLE
Deprecated v2 API signature

### ISSUE THREAD

**Issue by Zapmobilegames** [dpa99c/phonegap-launch-navigator#114]
This plugin seems need an update as in the console I read:

"launchnavigator.navigate() called using deprecated v2 API signature. Please update to use v3 API signature as deprecated API support will be removed in a future version"

**Comment by dpa99c** [comment]
You need to update your code to use the v3 **plugin** API signature, as documented [here](https://github.com/dpa99c/phonegap-launch-navigator#legacy-v2-api)
