### ISSUE TITLE
maps.me support

### ISSUE THREAD

**Issue by cordovapolymer** [dpa99c/phonegap-launch-navigator#118]
Can you add support of [maps.me](https://maps.me) ?
https://github.com/mapsme/omim/issues/5507

**Comment by dpa99c** [comment]
Looking at their documentation and source code, I'm not sure it's possible to launch maps.me in routing mode, let alone specify additional parameters such as start location and transport mode.

Let's see if someone comes back with an answer in the issue that you opened.

**Comment by dpa99c** [comment]
Unless/until maps.me provides a URL scheme which supports launching in routing mode, support will not be possible.

**Comment by cordovapolymer** [comment]
@dpa99c , thanks for your comments, I've bumped the issue on maps.me, hope we'll get the details.

**Comment by dpa99c** [comment]
If a satisfactory URL scheme is supplied, I'll reopen and implement.

**Comment by cordovapolymer** [comment]
@dpa99c
It will be finally implemented in maps.me https://github.com/mapsme/omim/issues/6386#issuecomment-314040726
 https://github.com/mapsme/api-android/wiki/Build-Route-and-Show-On-Map-via-Intent

**Comment by dpa99c** [comment]
@cordovapolymer  When it's implemented in their release, I will be able to implement and test it in this plugin.

**Comment by cordovapolymer** [comment]
@dpa99c , thanks!

**Comment by dpa99c** [comment]
@cordovapolymer I've done the bulk of implementation work for maps.me support for Android and iOS. It's currently on the [dev branch](https://github.com/dpa99c/phonegap-launch-navigator/tree/dev), until I have time to properly regression test and document it, but you can give it a try (`cordova plugin add https://github.com/dpa99c/phonegap-launch-navigator#dev`) and please feedback any issues you find.

**Comment by dpa99c** [comment]
This has now been released in v4.0.4
