### ISSUE TITLE
Capture my location as google maps start point

### ISSUE THREAD

**Issue by wuilmerj24** [dpa99c/phonegap-launch-navigator#119]
Hello, how can I make google maps have my starting point the location of the device?

**Comment by dpa99c** [comment]
As documented for the [navigate()](https://github.com/dpa99c/phonegap-launch-navigator#navigate) method:

> start (optional): start location to use for navigation. If not specified, the current device location will be used. 

i.e. omit the start parameter and it will default to the location of the device
