### ISSUE TITLE
ionic 2 app

### ISSUE THREAD

**Issue by timlitw** [dpa99c/phonegap-launch-navigator#120]
what do I import in my page to be able to use the launchnavigator.navigate?

**Comment by dpa99c** [comment]
You can either:

Reference the plugin via the [Ionic Native wrapper](https://ionicframework.com/docs/v2/native/launch-navigator/) - see the [Ionic2Example](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic2Example) in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example).

Or reference the plugin directly via the `launchnavigator` global namespace. The plugin includes a [type definition](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/uk.co.workingedge.phonegap.plugin.launchnavigator.d.ts) which you can import in order for Typescript to recognise the plugin API.
