### ISSUE TITLE
Launcher Navigation not working in android in eclipse

### ISSUE THREAD

**Issue by kanishkamehta801** [dpa99c/phonegap-launch-navigator#121]
Hello Team,

Please find the error below as launcher navigator is not working in android in eclipse.

**Plugin Used:** cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator

**Link of plugin:** https://github.com/dpa99c/phonegap-launch-navigator

**Library Added:** v3.6.0(okhttp3 library)

**Link of library:** http://square.github.io/okhttp/
![screen shot 2017-03-27 at 12 18 16 pm](https://cloud.githubusercontent.com/assets/26713798/24357519/90ac996c-131b-11e7-8cbf-ab7854d40c26.png)

**Error:**  

03-27 12:15:08.927: W/System.err(32008): java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
03-27 12:15:08.937: W/System.err(32008): 	at uk.co.workingedge.phonegap.plugin.LaunchNavigator.<init>(LaunchNavigator.java:113)
03-27 12:15:08.937: W/System.err(32008): 	at java.lang.Class.newInstanceImpl(Native Method)
03-27 12:15:08.937: W/System.err(32008): 	at java.lang.Class.newInstance(Class.java:1208)
03-27 12:15:08.937: W/System.err(32008): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:492)
03-27 12:15:08.937: W/System.err(32008): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
03-27 12:15:08.937: W/System.err(32008): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-27 12:15:08.937: W/System.err(32008): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-27 12:15:08.937: W/System.err(32008): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-27 12:15:08.937: W/System.err(32008): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-27 12:15:08.937: W/System.err(32008): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
03-27 12:15:08.937: W/System.err(32008): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 12:15:08.937: W/System.err(32008): 	at android.os.Looper.loop(Looper.java:136)
03-27 12:15:08.937: W/System.err(32008): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dpa99c** [comment]
This error indicates the [Gradle dependency](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L41) on the OkHTTP library has not been satisfied. If you build from the command-line using the Cordova CLI or using Android Studio, these Gradle dependencies are automatically satisfied. However, if you're using Eclipse IDE to build a Cordova project, you will have to figure out how to get it to work with Gradle.

Please try building and running the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) using the Cordova CLI for verification that the plugin itself works fine.

Closing this as it's not an issue with the plugin but with a non-standard build environment.
