### ISSUE TITLE
Sygic call doesn't work on iOS

### ISSUE THREAD

**Issue by munzeedaniel** [dpa99c/phonegap-launch-navigator#122]
Calling the Sygic app on iOS 10.0 or 10.3 doesn't work.

I found the old issue here https://github.com/dpa99c/phonegap-launch-navigator/issues/83
but since this was marked solved a year ago, I thought it's better to create a new issue.

Would be great if somebody could look into this. We'd highly appreciate a fix.

**Comment by dpa99c** [comment]
Sygic has probably made another backwardly-incompatible change to their URL scheme. I'll look into it when I have time.

**Comment by dpa99c** [comment]
No, my fault I somehow wiped out the changes which fixed Sygic in 5804b4c7303b7adf8887c0680c9eb2d3d60c6c2e with the changes to prevent unnecessary geocoding of addresses in 516ffd74b8afb8e645141ba35eca38d110cb944d.

Will fix and push out in a patch release.

**Comment by dpa99c** [comment]
Fix published in v3.2.2
