### ISSUE TITLE
availableApps() cannot get app which already installed

### ISSUE THREAD

**Issue by daoshenjay** [dpa99c/phonegap-launch-navigator#123]
Hi,I use this plugin in ionic2. 
When my android phone no map app exist, availableApps() function return null which is correct to me.
But if i goto decktop use home key,then install google map,and back to my app.Now availableApps() is still return null. Now this is a problem to me. Does there has some solutions for this situation?Thanks!

**Comment by dpa99c** [comment]
The plugin currently only performs discovery of installed apps at plugin initialization (app startup), so if the app is backgrounded, a supported navigation app is installed, then the app is resumed, the plugin will not refresh the list.

The plugin could be modified to expose its internal function to allow this to be re-invoked manually (e.g. on resume from background), but this would require an enhancement of the existing plugin functionality.

In the meantime, you can manually invoke the native plugin method to re-discover installed apps, for example:

	function discoverSupportedApps(){
		cordova.exec(
		    function(supportedApps){
				console.dir(supportedApps);
		    },
		    function(error){
				console.error(error);
		    },
		    'LaunchNavigator',
		    'discoverSupportedApps',
		    []
		);
	}
	document.addEventListener("resume", discoverSupportedApps, false);

After calling this, `launchnavigator.availableApps()` should return the updated list also.

**Comment by daoshenjay** [comment]
Hi,Dave,thanks for answering. I tryed your code, but it still not working. I see the plugin java code and find discoverSupportedApps()  get supported apps with variable availableApps not use intent to re-discover.
May this plugin support option to get available apps with intent?
