### ISSUE TITLE
PhoneGap Build Failure

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [dpa99c/phonegap-launch-navigator#124]
Followed your 'installation instructions' for phonegap build i.e. added the following to config.xml:

`<plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" source="npm" spec="3" />`

I am using the on-line Adobe PhoneGap Build service to build and install an APK on my Android 6.0.1 phone.

At run time, the "launchnavigator" is undefined.

What additional instructions should I be following?

**Comment by dpa99c** [comment]
> At run time, the "launchnavigator" is undefined.

Cordova dynamically loads plugins at runtime, so make sure you are not referencing the plugin namespace until after the `deviceready` event has fired.

> What additional instructions should I be following?

See the [Phonegap Build branch in the example project repo](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/phonegap_build)

**Comment by TriSysBusinessSoftware** [comment]
Thanks for your quick response. I goofed up and was not including
`<script src="cordova.js"></script>`
in my index.html.
When this is included, your plugin works well.

**Comment by dpa99c** [comment]
@TriSysBusinessSoftware Thanks for donation. It's really appreciated. If you have any problems/feedback, let me know.
