### ISSUE TITLE
use of undeclared identifier 'MKLaunchOptionsDirectionsModeTransit'

### ISSUE THREAD

**Issue by symmlbh** [dpa99c/phonegap-launch-navigator#125]
I'm using the plugin in my ionic project and I'm getting following error when I tried to build it in ios (simulator), may i know what's the problem? And how can I fix this? Sorry, I'm totally new in both ionic and phonegap. Hopefully someone can point me to the right direction. Thanks a lot. 

Following is the error I get:
Documents/ionicProject/togaPay/platforms/ios/togaPay/Plugins/uk.co.workingedge.phonegap.plugin.launchnavigator/CMMapLauncher.m:198:38: error: 
      use of undeclared identifier 'MKLaunchOptionsDirectionsModeTransit'
                    directionsMode = MKLaunchOptionsDirectionsModeTransit;
                                     ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/togaPay.build/Debug-iphonesimulator/togaPay.build/Objects-normal/i386/CMMapLauncher.o togaPay/Plugins/uk.co.workingedge.phonegap.plugin.launchnavigator/CMMapLauncher.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/IanLim/Documents/ionicProject/togaPay/platforms/ios/cordova/build-debug.xcconfig,-project,togaPay.xcodeproj,ARCHS=i386,-target,togaPay,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/IanLim/Documents/ionicProject/togaPay/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/IanLim/Documents/ionicProject/togaPay/platforms/ios/build/sharedpch

**Comment by dpa99c** [comment]
[MKLaunchOptionsDirectionsModeTransit](https://developer.apple.com/reference/mapkit/mklaunchoptionsdirectionsmodetransit) is a constant in the [MapKit](https://developer.apple.com/reference/mapkit) core iOS framework.

This plugin makes MapKit available by [specifying it as a required framework](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L63) so make sure in your Xcode project that MapKit.framework is present in Frameworks.

Also make sure you are using the latest version of the cordova-ios platform project: 

    cordova platform rm ios && cordova platform add ios@latest && cordova prepare ios

Finally, try building and running one of the examples in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) for reference and comparison.

**Comment by dpa99c** [comment]
Closing due to no response by OP
