### ISSUE TITLE
iOS open Maps problem

### ISSUE THREAD

**Issue by michelebravo** [dpa99c/phonegap-launch-navigator#126]
Hi!

Thank you for this nice plugin, it works fine on Android but I have problems with iOS. 
When I try to open the native navigation app nothing happens, but if I try to lock and then unlock the phone, the maps app is open.
I think it is a thread problem, could you help me, please?

**Comment by dpa99c** [comment]
This plugin works fine on all versions of iOS from 8.0 to 10.3.1 - you can try building and running one of the example apps in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to confirm this.

From the description of your problem, it sounds most likely that your Content Security Policy meta tag is causing the problem on iOS 10. Check out [my stackoverflow Q&A](http://stackoverflow.com/a/38410379/777265) on this topic for a solution if this is the case.

**Comment by michelebravo** [comment]
I have updated the Content Security Policy meta tag and now all works fine.
Thank you very much for your help and this incredible plugin!
