### ISSUE TITLE
comeback to main app after reaching destination (Automatically)??

### ISSUE THREAD

**Issue by ashutoshshukla1** [dpa99c/phonegap-launch-navigator#127]
Dear Developers, Many thanks for nice plugin. 

Please let me know if there has any way once we reach to destination, should come back to my app. 

1) User Launch "**MyApp**" and select navigation. 
2) The navigation app opens and launch direction. 
3) User reach to destination . Here i want to automatically open my "**MainApp**" on screen. 

Please let me know if its possible 

Thanks 
Ashu

**Comment by dpa99c** [comment]
Duplicate of #112
