### ISSUE TITLE
How to bind the destination nick name to search bar of some apps?

### ISSUE THREAD

**Issue by smchae** [dpa99c/phonegap-launch-navigator#128]
Hello,

First of all, thank you for this amazing plugin. However, I want to make one request. If I set destination as address, it binds its coordinate value to the search bar. But I noticed that when I add `destinationName` in the option, I get that in parenthesis. (e.g. 37.5759879, 126.976229(destinationName I specified) 

I want this feature because some the navigator apps does not support coordinate search, but only supports address.

If I were to customize it, which file should I look into?

Thank you.

**Comment by dpa99c** [comment]
How a navigation app displays the name of a destination is entirely in its control - this plugin has no influence over that; all it can do is to pass in the destination name (if supported) when launching the app, then it's up to that specific app how it handles display of a destination nickname.

You can look in the source code to see exactly how this plugin launches the navigation apps and what parameters are passed in: see [LaunchNavigator.java](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/android/LaunchNavigator.java) for Android and [CMMapLauncher.m](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/CMMapLauncher.m) for iOS.

**Comment by smchae** [comment]
@dpa99c I was able to achieve what I wanted by changing LaunchNavigator uri part. Thank you!
