### ISSUE TITLE
winphone not supported yet

### ISSUE THREAD

**Issue by bau720123** [dpa99c/phonegap-launch-navigator#13]
hi @dpa99c 
the page said it support (Windows Phone (Bing Maps))
http://plugins.cordova.io/#/package/uk.co.workingedge.phonegap.plugin.launchnavigator

but I tried in winphone，no any response (Android and iOS are work done)

by the way
the page said the plugin's Platforms is "windows" but not winphone

**Comment by dpa99c** [comment]
Hi @bau720123,

@opadro did the Windows implementation, and as he has stated in the plugin documentation:

"The plugin is compatible with Windows 8.1 on any PC and on Windows Phone 8.1 using the Universal .Net project generated by Cordova: `cordova platform add windows`"

This means is should be compatible with both Windows 8.1 on PC and Windows Phone 8.1 on mobile, but I assume not Windows Phone 7.x or 8.0 (correct me if I'm wrong @opadro).

Have you tried running the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) on your target device?

**Comment by bau720123** [comment]
hi @dpa99c 
thanks for your reply
but I am just use build.phonegap.com (cloud build)
so...I can't run your "example project"

**Comment by opadro** [comment]
Correct, @dpa99c , the plugin is not compatible with Windows Phone 7.x or 8.0. I have tested the plugin with a Stream 7 tablet, a Lumia 635, and custom build PC I use for developing. All running Windows 8.1 (and Windows Phone 8.1 in the case of the Lumia)

@bau720123 I have run into problems using PhoneGap Build for Windows because there are some differences between the JavaScript you can run in a browser and a Windows 8.1 app. For example, alert() is not available in Windows 8.1. PhoneGap build will not warn you about this. Try debugging in your Windows PC if possible.

**Comment by bau720123** [comment]
hi @dpa99c and @opadro 
but see the PGB's plugin page
https://build.phonegap.com/plugins/2285
it only support Android and iOS (I am using PGB)
and...
the cordova.io page (android, ios, windows)
PS，windows is not wp8 or wp8.1
http://plugins.cordova.io/#/package/uk.co.workingedge.phonegap.plugin.launchnavigator

**Comment by opadro** [comment]
@bau720123 I don't know what is exact the error you are receiving. If you can share that, it will be easier to help you (screencap, stack trace, etc.). In addition, you have to make sure your JavaScript is compatible with `windows` JavaScript. The JavaScript that runs fine in the browser, iOS, or Android, will not work in `windows`. For example, the alert() method is not available in `windows`.  PGB will not complain and it will build you a xap file anyway. I can assure you it is not validating that your JavaScript is compatible with `windows`. I have tested this myself.

I recommend you debug your app in your PC before using PGB. Install Visual Studio 2013 Community Edition and add the platform manually using Cordova: `cordova platform add windows`: https://cordova.apache.org/docs/en/5.0.0/guide_cli_index.md.html#add-platforms

Finally, in Cordova, the `windows` platform *is* compatible with wp8.1: 
https://cordova.apache.org/docs/en/5.0.0/guide_platforms_win8_index.md.html

**Comment by dpa99c** [comment]
@bau720123 As @opadro says, using Visual Studio will allow you to debug your code. And you can also use it to run the example project in an emulator to reassure yourself that the plugin works correctly.

**Comment by bau720123** [comment]
hi @dpa99c and @opadro 
I know you meaning
but I just use PGB (build.phonegap.com) (not cordova cli)
in PGB's environment there is no way to use Visual Studio
I just want to said that and it is really not work in PGB's winphones's environment

**Comment by dpa99c** [comment]
@bau720123  I suggest you add some [try/catch statements](http://www.w3schools.com/js/js_errors.asp) to catch any errors in your code and use [console functions](https://developer.mozilla.org/en-US/docs/Web/API/Console) to log them out, then use the [remote debugging tools](http://docs.build.phonegap.com/en_US/2.9.0/debugging_remote_debugging_tools.md.html) available on Phonegap Build to debug your code.

@opadro I am able to run the example project on my local machine in the Windows Phone 8.1 emulator via Visual Studio. It works fine - good job! So shall we close this issue?

**Comment by bau720123** [comment]
hi @dpa99c 
thanks for your reply
ok~
close it first
thanks again

**Comment by visnupriya** [comment]
@dpa99c and @opadro  For me it is not working on WP8.1 device. I am using Nokia Lumia 630 - OS WP 8.1 update. After added this plugin directly from github, I ran the app using Visual Studio. It is throwing error as "ERROR:ReferenceError: 'launchnavigator' is undefined". Anything I missed? It works fine on Android and IOS.  Please help me.

**Comment by Madan2829** [comment]
Hi,
@dpa99c @opadro I have been ran into a similar problem, but not with launchnavigator object. I have been getting an error callback saying "_ReferenceError: **Windows **is undefined_". I tried to figure out, but did not find a solution.
I am Using Windows 8.1 Phone and also a Windows 10 Phone (Lumia 925 and Lumia 1520 respectively). I have checked the "src" and "www" folders in plugin, and _did not find any folder related to windows in **src**_. And there is "_launchnavigator.js_" file in "_www/windows_". 

So do i have to add anything else to make the plugin work on Windows Phone?
Plugin is working great in Android, But i am facing this issue in Windows Phone. Kindly suggest me some solution for this issue.

please look into the following image for the callback message:

![wp_ss_20160408_0001](https://cloud.githubusercontent.com/assets/16935357/14378482/c1a239ae-fd92-11e5-8f7c-b3953b1df214.png)


Thanks in advance

**Comment by dpa99c** [comment]
I'll have a look into it when I get some time

**Comment by dpa99c** [comment]
@Madan2829 Looks like I introduced a bug to Windows Phone 8. I'll publish a fix in the next release.
