### ISSUE TITLE
Not working IOS10

### ISSUE THREAD

**Issue by Studiotekst** [dpa99c/phonegap-launch-navigator#135]
Hello people,

I have a question.
I installed this plugin with the following line:
cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator

In my config.xml file this line is visible:
<plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="~3.2.2" />

Plugin is also visible in plugins folder and node_modules folder.
And also in browser.json this line is visible:
 "uk.co.workingedge.phonegap.plugin.launchnavigator": {
            "PACKAGE_NAME": "com.phonegap.helloworld"
        }
In my application i call the function this way:
 <div style="height: 150px; width: 250px;background-color: red;" ng-click="startNav()">Nav!</div>

And this is the function it calls:
   $scope.startNav = function(){
        launchnavigator.navigate("London, UK", {
            start: "Manchester, UK"
         });
    }

Despite the part "launchnavigator" is highlighted the app is not working. 
Nothing happens when clicking the button. When i put an alert() inside the function, the alert is visible.
Currently i'm running on IOS 10.3.2

I have also tried the examplecode but this is unfortunately not working to..

Can you please help me?

**Comment by dpa99c** [comment]
> I have also tried the examplecode but this is unfortunately not working to..

Did you try building and running one of the projects from the [example repo](https://github.com/dpa99c/phonegap-launch-navigator-example)?

The plugin has been tested using these and verified as working on iOS 10.3.2

**Comment by Studiotekst** [comment]
Thank you for you're response.
Yes i tried the simpleExample a couple of times but every time when i click on 'Navigate' button, nothing happens. The same problem when i click on 'Navigate' in my own project..:(

This is how i call the function in my own project. May it be a setting in my iphone maybe?
`$scope.startNav = function(){
        launchnavigator.navigate("London, UK", {
            start: "Manchester, UK"
         });
    }`

**Comment by dpa99c** [comment]
[Here is a screencast](http://ge.tt/3Z5TBUl2) of the SimpleExample running on my iPad with iOS 10.3.2.

You'll need to debug it within your build/run environments to find why it's not working for you. I suggest connecting Safari Web Inspector to the Webview to check for JS errors. If that doesn't help, run the app from XCode and check the native console output for errors.

**Comment by Studiotekst** [comment]
Thanks for your commit again.
When i click the button (in the example project) i get this error (see image):
![img_6427](https://user-images.githubusercontent.com/29227109/27434287-81656872-5758-11e7-84cc-c4cd0360c9e1.PNG)

**Comment by dpa99c** [comment]
It looks like you are running your app inside of the [Phonegap Developer App](http://docs.phonegap.com/references/developer-app/) instead of building and running a native iOS app via XCode or the Cordova CLI.

This will **not work** with this plugin because it contains native code which must be baked into the native app at build time.

**Comment by Dhamu143** [comment]
i am aslo facing the same issue. is there any update on it? its perfectly working on android but gives same error for IOS
