### ISSUE TITLE
please correct the type of launchnavigator.d.ts

### ISSUE THREAD

**Issue by JohnKimDev** [dpa99c/phonegap-launch-navigator#136]
The `launchnavigator` type is incorrectly declared as `any`. The correct type should be "LaunchNavigator". Please update the code in launchnavigator.d.ts

`declare var launchnavigator: LaunchNavigator;`

**Comment by dpa99c** [comment]
This was fixed by commit 459d4f10b53d518a7cdcb78519f960d45ea17ecd and published in v4.0.0, as can be seen on [the master branch](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/launchnavigator.d.ts)
