### ISSUE TITLE
Error on iOS.

### ISSUE THREAD

**Issue by pmwisdom** [dpa99c/phonegap-launch-navigator#14]
I'm getting this error while trying to launch the maps app on an iOS device, primarily iPhone 4s, and iPhone 5 (dont have any other phones at my disposal). 

2015-05-04 09:00:31.702 FlyBuy[8930:608532] Navigator succesfully launched maps application <-- This is the success callback
2015-05-04 09:00:31.715 FlyBuy[8930:608532] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument

And this is the pattern i'm using:

 launchnavigator.navigate(
            [47.614651 -122.314252],
            [47.61528546427107 -122.3148449229748],
            function(){
                console.log("Navigator succesfully launched maps application");
            },
            function(error){
                console.log("There was an error opening the maps application", error);
            });

Any thoughts?

**Comment by dpa99c** [comment]
If the code you posted is exactly what you are using, then you are missing the commas in the coordinate arrays. The values should be comma separated, I.e.

[47.614651, -122.314252],
[47.61528546427107, -122.3148449229748],

**Comment by pmwisdom** [comment]
Sorry I do have commas in there, I pasted the coordinates from goog maps.. It works perfectly on android .

**Comment by pmwisdom** [comment]
This is my exact code:

  launchnavigator.navigate(
            [currentDestination.coordinates[1], currentDestination.coordinates[0]],
            null,
            function(){
                console.log("Navigator succesfully launched maps application");
            },
            function(error){
                console.log("There was an error opening the maps application", error);
            });

**Comment by dpa99c** [comment]
The call signature looks correct, but obviously I can't see the values of `currentDestination` - I would suggest logging `currentDestination.coordinates[1]` and `currentDestination.coordinates[0]` to the console to confirm they are not null.

**Comment by pmwisdom** [comment]
@dpa99c Yep made sure they werent null too. And just to be sure, those coordinates above that I posted, I hardcoded those just now, I got the same error.

**Comment by dpa99c** [comment]
What version of iOS are you testing on? I haven't tested the plugin on the latest iOS 8.3, so it's possible there's an issue caused by this update - it worked fine on 8.2 when I tested it.

Are you able to build and run the example project in XCode and confirm this works or not?

**Comment by pmwisdom** [comment]
I'm on 8.1.1, on an iPhone 4s. I'll go ahead and build the text project and let you know.

**Comment by pmwisdom** [comment]
Well, that went and worked. Weird. I'm not sure whats up then.

**Comment by pmwisdom** [comment]
Ah I think I figured it out, by looking at what version you had in your demo project. I took the version from the plugin.xml in this git as the latest version (2.1.0) but the cordova registrys latest version is actually 2.2.0. I'm gonna update and ill report back.

**Comment by pmwisdom** [comment]
Figured it out, something wrong with my access rules. When I set accessRule to * it worked. I should only have to add geo: to my access rules correct?

**Comment by dpa99c** [comment]
The plugin only uses the geo: URL namespace, so unless you need access to any other URL-based resources, you can just set `<access origin="geo:*" />`

**Comment by dpa99c** [comment]
I'll add something to the README.md when I get a sec about allowing access to geo namespace

**Comment by dpa99c** [comment]
Sorry, just looked at the code again and on iOS it uses `maps:` so `<access origin="maps:*" />`

**Comment by pmwisdom** [comment]
I tried these three:
<access origin="maps:*" />
<access origin="geo:*" />
<access origin="comgooglemaps:*" />

Which didn't solve the problem for some reason. 

Let me try to do that in the demo project.

**Comment by pmwisdom** [comment]
OK, I'm going to close this as something wrong with Meteor / Cordova integration, it works fine in regular cordova, even without the access rules.

**Comment by dpa99c** [comment]
OK, thanks for looking into it
