### ISSUE TITLE
appSelection optional parameter not working

### ISSUE THREAD

**Issue by jyotigupta007** [dpa99c/phonegap-launch-navigator#140]
Hello,
I want to limit the number of map application to be shown on the action sheet when selecting the map application to only launchnavigator.APP.GOOGLE_MAPS
launchnavigator.APP.WAZE and launchnavigator.APP.APPLE_MAPS. I tried it by passing optional parameter "appSelection" in launchnavigator.navigate(destination, options). In the object "appSelection" I passed "list" as an array with above mentioned names. But it seems the code is not working...Its neither giving any error. It had no effect of the code. I am really eager and in a hurry to know the correct approach to achieve this task. 
Please reply ASAP
Thanks

**Comment by dpa99c** [comment]
The list should be passed as `options.appSelection.list`, for example:

    launchnavigator.navigate("London", {
        appSelection:{
            list: [
                launchnavigator.APP.GOOGLE_MAPS,
                launchnavigator.APP.WAZE,
                launchnavigator.APP.APPLE_MAPS
            ]
        }
    });

A working example can be seen in the `AdvancedExample` in the [example project repo](https://github.com/dpa99c/phonegap-launch-navigator-example) which [illustrates usage of this option](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L134)

![image](https://user-images.githubusercontent.com/2345062/28163740-55b1ef6c-67c4-11e7-9ff4-ed8cb9ee9ea1.png)

![image](https://user-images.githubusercontent.com/2345062/28163781-7086b426-67c4-11e7-94d5-743287c272da.png)

**Comment by jyotigupta007** [comment]
Hello, 
I am grateful for your reply but it still does not work. Let me tell you that I am using it in ionic+angular phone application. I have tried all ways of coding like :- 
***
launchnavigator.navigate([payload.r_des_lat,payload.r_des_lng], appSelectionCallback , {appSelection:{list: [launchnavigator.APP.GOOGLE_MAPS]}});  ==> doesnot work, no action sheet is launched the screen gets hanged

launchnavigator.navigate([payload.r_src_lat,payload.r_src_lng], { appSelectionCallback , appSelection:{list: [ launchnavigator.APP.GOOGLE_MAPS]}}); ==> launchnavigator works..but app selection is not working...all the apps get listed 
launchnavigator.navigate([payload.r_des_lat,payload.r_des_lng], {appSelection:{list: [launchnavigator.APP.GOOGLE_MAPS]}}); ==> doesnot work, no action sheet is launched the screen gets hanged

***

**Comment by dpa99c** [comment]
Please make sure you are using the most recent version of the plugin (v4).

Also please confirm whether you are able validate that the plugin is working within the example project.

**Comment by dpa99c** [comment]
Closed due to no response from OP

**Comment by Alb93** [comment]
Also here problem with Android device on options passed to navigate method.
The plugin version is 4.0.2 and I use it with ionic framework.

My intent is to change the text shows by the plugin (i.e. dialogHeaderText) but no attempts were succesful.

**Comment by dpa99c** [comment]
@Alb93 This can be [seen working](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L132) in the AdvancedExample in the [example repo](https://github.com/dpa99c/phonegap-launch-navigator-example).

If you are using Ionic Native, make sure the Typescript wrapper is up-to-date as the options object structure has changed in v4 of this plugin.

**Comment by Alb93** [comment]
@dpa99c How I can check this?

I've downloaded the plugin by following the ionic standard guide about 2 days ago. I've tried to replicate the object structure in this way
 `  let opts:LaunchNavigatorOptions = {
        appSelection:{
            dialogHeaderText: "Custom header",
            cancelButtonText: "Custom cancel text"
        }
};`

and in some other ways but still nothing.

**Comment by dpa99c** [comment]
It's possible there's a bug in the updated Ionic Native Typescript wrapper when it comes to mapping of the revised options object. You can try invoking the plugin directly:

    declare var launchnavigator : any;

    launchnavigator.navigate("some destination", {
        appSelection:{
            dialogHeaderText: "Custom header",
            cancelButtonText: "Custom cancel text",
        }
    });

I would recommend debugging the JS by connecting a remote debugger session to the Webview (Safari/Chrome).

**Comment by Alb93** [comment]
>  `declare var launchnavigator : any;`

This is nice and seems to work well.

How and where I can report the presumable "bug in the updated Ionic Native Typescript wrapper "?

**Comment by dpa99c** [comment]
Typescript wrapper [is here](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts) so you can open any issues [here](https://github.com/ionic-team/ionic-native/issues).
