### ISSUE TITLE
Start location is of no use

### ISSUE THREAD

**Issue by abdul-basit0** [dpa99c/phonegap-launch-navigator#145]
When i create a build or use the same code for navigation between two locations, it ignores the start location and use current location instead.

**Comment by dpa99c** [comment]
This is not enough information: for example which navigation apps are encountering the issue, what plugin version, what platform?

This plugin has been thoroughly regression tested, so most likely you are specifying the wrong input parameter for start location. Please see the [example repo](https://github.com/dpa99c/phonegap-launch-navigator-example) which contains several Cordova projects which illustrate how to use the plugin, for example the [SimpleExample](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/SimpleExample) shows how to [specify the start location](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/SimpleExample/www/index.js#L23). Please try building and running the example projects to validate this.

**Comment by abdul-basit0** [comment]
Sir i have even created the build of your code but its not working as shown in demo..

**Comment by abdul-basit0** [comment]
It doesn't even bother what is in the "Start" variable

**Comment by dpa99c** [comment]
Please give the following info:

Platform: Android or iOS?
Plugin version? (e.g. 4.0.3)
Navigation app? (e.g. Google Maps)
Plugin interface? (Ionic Native or pure JS)

Code example of your call to the plugin, for example:

    launchnavigator.navigate(dest, {
        start: start,
        enableDebug: true
    });

**Comment by abdul-basit0** [comment]
Platform : Android
Navigation app: Google Maps
Plugin interface: Ionic 2

downloaded it from here
https://ionicframework.com/docs/native/launch-navigator/

**Comment by dpa99c** [comment]
OK, I will have a look at this when I get some time. It may be a bug in the Ionic Native wrapper for this plugin.

**Comment by dpa99c** [comment]
It looks like this is being caused by mismatch in how parameters are mapped between ionic-native@4 and this plugin. These easiest thing is for me to create a patch release of the plugin which will map the ionic-native parameter structure to the structure expected by this plugin.

**Comment by dpa99c** [comment]
I've just published a patch release - v4.0.4 - which fixes this issue when using the plugin with Ionic Native v4.
