### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by ThisIsAPseudo** [dpa99c/phonegap-launch-navigator#147]
Hi!
First, thanks for this plug-in. 
I want to use it in an app, but for french people. Do you mind if I suggest you a way to translate your front messages in an other language, according to the app or the device current language?
Kind regards

**Comment by dpa99c** [comment]
I'm not sure what text you are referring to, but it should be possible to override all of the default English messages with translated version using the options object passed to the [`navigate()`](https://github.com/dpa99c/phonegap-launch-navigator#navigate) function, for example `dialogHeaderText`, `headerText`, `bodyText`, etc.

**Comment by ThisIsAPseudo** [comment]
(www/common.js -> messages here)

**Comment by dpa99c** [comment]
As I've said above, as far as I'm aware all the default messages can be overridden with a translated version by specifying the appropriate keys in the options object passed to the `navigate()` function. 

If you think there is a default message which cannot be overridden, please post the default English message which you are not able to change so I will know what message you are referring to.

**Comment by dpa99c** [comment]
Closed due to no response from OP
