### ISSUE TITLE
Custom header text

### ISSUE THREAD

**Issue by abdul-basit0** [dpa99c/phonegap-launch-navigator#150]
Is it possible to change the color of the custom headertext?
![screenshot_20170821-124034](https://user-images.githubusercontent.com/28341313/29509186-d0708fb8-8670-11e7-9734-f018fc57dfab.png)

I want to change the color of header from blue to any other color

**Comment by dpa99c** [comment]
No, it's no possible using the default plugin UI.
The plugin uses [cordova-plugin-actionsheet](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet) to provide a simple out-of-the-box UI and it doesn't support changing the text color. If you want to change the text color, you are best creating your own UI to display the list of apps returned by [availableApps()](https://github.com/dpa99c/phonegap-launch-navigator#availableapps).
