### ISSUE TITLE
navigation without using native application of android/ios

### ISSUE THREAD

**Issue by Dhamu143** [dpa99c/phonegap-launch-navigator#151]
I have used this plugin for navigation but it opens native apps of the devices, is there any way that we do not need to open native apps and we can develop navigation in our app it self?

I have tried all things you can check here

https://stackoverflow.com/questions/45930997/real-time-google-navigation-in-cordova-phonegap-for-hybrid-application-ionic1

please do reply I am stuck on this issue.

**Comment by dpa99c** [comment]
This issue is not relevant to this plugin
