### ISSUE TITLE
Support for Cabify App

### ISSUE THREAD

**Issue by pedrohills** [dpa99c/phonegap-launch-navigator#155]
Please add support for Cabify app in iOS and Android platforms.

The link details can be found at:

http://developers.cabify.com/#mobile-deeplink

Thanks.

**Comment by dpa99c** [comment]
@pedrohills this has been implemented on the [dev branch](https://github.com/dpa99c/phonegap-launch-navigator/tree/dev), but the iOS implementation is failing to launch the Cabify app using the documented URL scheme (see the issue above).

**Comment by dpa99c** [comment]
Implemented and published `uk.co.workingedge.phonegap.plugin.launchnavigator@4.0.6`. 
Note the iOS URL scheme is still not working as of Cabify app v6.3.3

**Comment by emyymk** [comment]
Hi, i need Cabify support on IOS. 
Please, is it possible to see if the iOS URL scheme has been implemented on this new version (Cabify app is v7.1.5)?

**Comment by dpa99c** [comment]
Just tested Cabify v7.1.4 for iOS (latest available in App Store) and the issue remains the same: calling the `cabify://` URL scheme does not launch the app.

In testing this, I realised I'd forgotten to add the native iOS constants for Cabify and Baidu Maps which meant the apps were always being reported as not installed: I've just published a patch version - 4.1.4 - which fixes this.

So you can now test this yourself, for example using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) and see that the correct native URL is called but the Cabify app does not respond to it.

**Comment by dpa99c** [comment]
The above data structure is actually identical to the documentation and hence still doesn't work with the latest version of the iOS app. However, I've received the following email from Cabify so I will anticipate that the next release of Cabify iOS will fix the URL scheme:

>Alfonso Rocha <alfonso.rocha@cabify.com>
>6 March 2018 at 10:06
>Hello Dave,
>
>Thanks for reporting this. We've seen this issue, fixed it and we will push to production soon the new version.
>
>We're sorry for the problems it may caused to you and your userbase.
>
>Cheers,
>
>Cabify - Your private Driver	
>Alfonso Rocha
>Product Manager
>
>alfonso.rocha@cabify.com
>+34 684 25 69 52

**Comment by pedrohills** [comment]
I am very happy to hear this feedback.

**Comment by dpa99c** [comment]
FYI I just tested Cabify v7.1.5 for iOS (released yesterday, March 8) and it still does not launch when the URL scheme is invoked.

This was the URL which the plugin constructed:

    cabify://cabify/journey?json={"stops":[{"loc":{"longitude":"-5.982372","latitude":"37.388140"},"name":"Seville"},{"loc":{"longitude":"-3.701690","latitude":"40.434233"},"name":"Madrid"}]}

**Comment by dpa99c** [comment]
Published in v4.2.0

**Comment by emyymk** [comment]
Thank you, dpa99c. 
Working fine on IOS.
