### ISSUE TITLE
specific transport mode

### ISSUE THREAD

**Issue by Dhamu143** [dpa99c/phonegap-launch-navigator#157]
how can get specific transport mode 
launchnavigator.navigate([50.279306, -5.163158], {
    start: "50.342847, -4.749904"
};

there is no example of how to use this.. please edit above code with specific transport mode

TRANSPORT_MODE

Transport modes for navigation:

    launchnavigator.TRANSPORT_MODE.DRIVING
    launchnavigator.TRANSPORT_MODE.WALKING
    launchnavigator.TRANSPORT_MODE.BICYCLING
    launchnavigator.TRANSPORT_MODE.TRANSIT

**Comment by dpa99c** [comment]
Use of the transport mode parameter is illustrated [here](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L21) and [here](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L129) in the [AdvancedExample]().

i.e.

    launchnavigator.navigate([50.279306, -5.163158], {
      start: "50.342847, -4.749904",
      transportMode: launchnavigator.TRANSPORT_MODE.WALKING
    };

See also the [Transport Mode documentation](https://github.com/dpa99c/phonegap-launch-navigator#transport-modes).

**Comment by Dhamu143** [comment]
I recently tried this but did not work. i am using android device.

**Comment by dpa99c** [comment]
Please try building+running the AdvancedExample for confirmation that this works.
Note the [constraints](https://github.com/dpa99c/phonegap-launch-navigator#android), i.e. Google Maps must be launched in turn-by-turn mode in order to accept transport mode.

**Comment by Dhamu143** [comment]
how can I enable that Turn-by-turn mode ? please edit above example please

**Comment by Dhamu143** [comment]
is it possible that we can show only train in transportation mode ? if yes then how ?

**Comment by Cowprod** [comment]
Hi, 

Walking mode works with this code, but if I use launchnavigator.TRANSPORT_MODE.TRANSIT , driving mode is selected.
The problem is the same in myapp and advanced example project
 (Android / Maps App with cordova)

**Comment by eduboxgithub** [comment]
I also noticed this... launchnavigator.TRANSPORT_MODE.TRANSIT works the same way like the DRIVING.
