### ISSUE TITLE
Reachability namespace collides with cordova-plugin-network-information

### ISSUE THREAD

**Issue by geejay101** [dpa99c/phonegap-launch-navigator#162]
The name _kReachabilityChangedNotification causes a duplicate symbol error when used with  cordova-plugin-network-information.

Please change to avoid conflict.

Thanks for this great plugin.

**Comment by dpa99c** [comment]
Fixed on master by #161 and will be published shortly to npm

**Comment by geejay101** [comment]
great thanks

**Comment by dpa99c** [comment]
Fix published in v4.0.7
