### ISSUE TITLE
What about localization?

### ISSUE THREAD

**Issue by sstraus** [dpa99c/phonegap-launch-navigator#167]
Hi, there is a way to translate "select app for navigation" or "cancel"?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/phonegap-launch-navigator#navigate):

>- {object} - appSelection - options related to the default native actionsheet picker which enables user to select which navigation app to launch if `app` is not specified.
>    - {string} dialogHeaderText - text to display in the native picker body, above the app buttons.
>      - Defaults to "Select app for navigation" if not specified.
>    - {string} cancelButtonText - text to display for the cancel button.
>      - Defaults to "Cancel" if not specified.
