### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by RobJmz** [dpa99c/phonegap-launch-navigator#169]
I would like to know if there is a way to add waypoints as we launch google maps?

Documentation doesn't shows any way to do this...

I found out issue #98 workaround, but doesn't seem to work anymore.

If this issue shouldn't be open please re-open #98 
Thanks in advance

**Comment by dpa99c** [comment]
There is no officially documented way of specifiying intermediary waypoints in the Google Maps [Android](https://developers.google.com/maps/documentation/urls/android-intents#launch_turn-by-turn_navigation) and [iOS](https://developers.google.com/maps/documentation/urls/ios-urlscheme#add_navigation_to_your_app) app documention.

However, the workaround described by @rameshsr in #98 still appears to work:

For example, calling the plugin with:

    launchnavigator.navigate("Manchester+to:Birmingham+to:London",{
        app: launchnavigator.APP.GOOGLE_MAPS,
        start: "Glasgow",
    });

Results in invoking the Android app with the URL:

    http://maps.google.com/maps?daddr=Manchester+to:Birmingham+to:London&saddr=Glasgow

which opens the Google Maps Android app (v9.67.1) with the waypoints:

<img width="300" src="https://user-images.githubusercontent.com/2345062/33675535-ca375c6a-daaa-11e7-9c13-e90d657c0b20.png" />

And invoking the iOS app (v4.41) with the URL:

    comgooglemaps://?daddr=Manchester+to:Birmingham+to:London&saddr=Glasgow&directionsmode=driving

which opens the Google Maps iOS app with the waypoints:

<img width="300" src="https://user-images.githubusercontent.com/2345062/33675577-ed132a70-daaa-11e7-94bb-b4fd75212137.png" />

Therefore closing this as the original workaround still appears to work.

**Comment by RobJmz** [comment]
I tried to do exactly the same with  "+to" using coordinates, although is not working, it shows me on destination:
"25.669511,-100.374177+to25.667228,-100.382615" showing no results at all...

**Comment by dpa99c** [comment]
It looks like you are missing the colon, i.e. you have `+to` instead of `+to:`

 Try:

    "25.669511,-100.374177+to:25.667228,-100.382615"

**Comment by RobJmz** [comment]
Oh, you are 100% correct, that was my fault. Thanks a lot for the great work! Excellent plugin.

**Comment by cmargulhano** [comment]
Is this still working?

**Comment by MarkJAmes1217** [comment]
Any Updates ????

**Comment by dpa99c** [comment]
Try the workaround as described above. 
If it doesn't work, it's because Google Maps has removed support for this undocumented feature.

**Comment by ratikanta131** [comment]
It is still working! Thanks.
