### ISSUE TITLE
Good way to translate

### ISSUE THREAD

**Issue by nitrique** [dpa99c/phonegap-launch-navigator#174]
Hi,
In first, thank you so much for your work !

Can we have a good method to translate this:

```
var DEFAULT_appSelectionDialogHeaderText = "Select app for navigation",
    DEFAULT_appSelectionCancelButtonText = "Cancel",
    DEFAULT_rememberChoicePromptDialogHeaderText = "Remember your choice?",
    DEFAULT_rememberChoicePromptDialogBodyText = "Use the same app for navigating next time?",
    DEFAULT_rememberChoicePromptDialogYesButtonText = "Yes",
    DEFAULT_rememberChoicePromptDialogNoButtonText = "No";
```

Nicolas

**Comment by dpa99c** [comment]
This is [documented](https://github.com/dpa99c/phonegap-launch-navigator#navigate) in the options for `navigate()`, for example:

    launchnavigator.navigate(destination, {
        appSelection: {
            dialogHeaderText: "Select app for navigation",
            cancelButtonText: "Cancel",
            rememberChoice: {
                prompt: {
                    headerText: "Remember your choice?",
                    bodyText: "Use the same app for navigating next time?",
                    yesButtonText: "Yes",
                    noButtonText: "No"
                }
            }
        }
    });
