### ISSUE TITLE
Plugin not installing on android and ios using phonegap build

### ISSUE THREAD

**Issue by Maheshbhusanoor** [dpa99c/phonegap-launch-navigator#175]
Till yesterday everything was working fine.But when i started building app on today i am getting following error for navigator plugin.
 
i am using following configuration
`<plugin spec="https://github.com/dpa99c/phonegap-launch-navigator.git" /> `

Phonegap cli-7.0.1 (Ios cordova 4.4.0 /Android cordova-6.2.3)

Here is the error message
`
Error - Plugin error (you probably need to remove plugin files from your app): //github.com/dpa99c/phonegap-launch-navigator.git --nohooks=.": Fetching plugin "https://github.com/dpa99c/phonegap-launch-navigator.git" via git clone Using shallow clone Repository "https://github.com/dpa99c/phonegap-launch-navigator.git" checked out to git ref "master" at "d55752b". Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" at "4.1.0" for android Fetching plugin "cordova-plugin-actionsheet@2" via npm Installing "cordova-plugin-actionsheet" at "2.3.3" for android Failed to install 'uk.co.workingedge.phonegap.plugin.launchnavigator': CordovaError: Version of installed plugin: "cordova-plugin-dialogs@2.0.0" does not satisfy dependency plugin requirement "cordova-plugin-dialogs@^1". Try --force to use installed plugin as dependency. at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:581:33 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:509:49 at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9) Version of installed plugin: "cordova-plugin-dialogs@2.0.0" does not satisfy dependency plugin requirement "cordova-plugin-dialogs@^1". Try --force to use installed plugin as dependency.`

**Comment by dpa99c** [comment]
This was caused by a [major version update](http://cordova.apache.org/news/2017/12/20/plugins-release.html) to most of the core cordova plugins yesterday, including `cordova-plugin-dialogs` to `2.0.0`, while this plugin [currently depends on `1.x`](https://github.com/dpa99c/phonegap-launch-navigator/blob/4.1.0/plugin.xml#L56).

Since I still want it to work with `cordova-plugin-dialogs@1` as well as the new `cordova-plugin-dialogs@2`, I'll unpin the dependency to `cordova-plugin-dialogs@*`, which should resolve your issue.

**Comment by Maheshbhusanoor** [comment]
Ok thank you so much.
