### ISSUE TITLE
Plugin not intsalling on Android and Ios

### ISSUE THREAD

**Issue by Maheshbhusanoor** [dpa99c/phonegap-launch-navigator#176]
Hello Sir,

Thank you for updating plugins but Still i am getting same error as  i was getting in version 4.1.0.

Here is the error code
`
Error - Plugin error (you probably need to remove plugin files from your app): //github.com/dpa99c/phonegap-launch-navigator.git --nohooks=.": Fetching plugin "https://github.com/dpa99c/phonegap-launch-navigator.git" via git clone Using shallow clone Repository "https://github.com/dpa99c/phonegap-launch-navigator.git" checked out to git ref "master" at "d115e93". Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" at "4.1.1" for android Fetching plugin "cordova-plugin-actionsheet@2" via npm Installing "cordova-plugin-actionsheet" at "2.3.3" for android Failed to install 'uk.co.workingedge.phonegap.plugin.launchnavigator': CordovaError: Version of installed plugin: "cordova-plugin-dialogs@2.0.0" does not satisfy dependency plugin requirement "cordova-plugin-dialogs@^1". Try --force to use installed plugin as dependency. at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:581:33 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:509:49 at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9) Version of installed plugin: "cordova-plugin-dialogs@2.0.0" does not satisfy dependency plugin requirement "cordova-plugin-dialogs@^1". Try --force to use installed plugin as dependency.`

**Comment by dpa99c** [comment]
Ah crap, I just spotted it was [referenced again](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L32) in the `plugin.xml`. Will publish another version which fixes this.

**Comment by Maheshbhusanoor** [comment]
For ios its getting bulid.I am facing problem  for android only now.Thank you for your quick response.

**Comment by dpa99c** [comment]
`uk.co.workingedge.phonegap.plugin.launchnavigator@4.1.2` should now work for both Android and iOS

**Comment by Maheshbhusanoor** [comment]
ok thank you so much.I will check now.

**Comment by Maheshbhusanoor** [comment]
Waaw!! Perfect.Its working.Thank you so much.
