### ISSUE TITLE
Error launching navigator: plugin_not_installed

### ISSUE THREAD

**Issue by gbhopal** [dpa99c/phonegap-launch-navigator#178]
I am trying the user to a maps app on their device using `launch-navigator` for ionic. I have installed the Cordova plugin using `ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`, however when i try and run function i get 

> Error launching navigator: plugin_not_installed

In my config.xml, i do have the plugin stated and also included it in app.modules.ts 

locations.ts code

    this.platform.ready().then(()=>{
      this.launchNavigator.navigate("London, UK")
        .then(
          success => alert('Launched navigator'),
          error => alert('Error launching navigator: ' + error)
        );
    });

**Comment by kefimo** [comment]
any news?
