### ISSUE TITLE
 apple Maps audio and other options are not working  

### ISSUE THREAD

**Issue by venkatan91** [dpa99c/phonegap-launch-navigator#181]

**Comment by dpa99c** [comment]
This is not sufficient information to open an issue.

If you are reporting a bug relating to existing plugin functionality, please give:
- details of expected behaviour vs actual behaviour
- steps (e.g. plugin input parameters) to reproduce the issue
- environment details (Apple Maps version, iOS version)

If you are requesting a new feature/functionality, please give a detailed outline of the proposed addition including links to relevant native API documentation where relevant.

Failure to give the above details will result in the issue being deemed invalid and it will be closed.

**Comment by venkatan91** [comment]
apple native maps 
![img_4134](https://user-images.githubusercontent.com/36213787/35925074-c9de932c-0bf2-11e8-96b6-f82cf42966cb.PNG)

launching the apple maps after using the plugin 
![img_4132](https://user-images.githubusercontent.com/36213787/35925131-ee9689ea-0bf2-11e8-8822-091387c82c90.PNG)
I read the documentation to change the default mode URI_SCHEME to MAPKIT .I changed the mode but nothing worked.

 startExternalMap() {
      

        let options: LaunchNavigatorOptions = {
              start: [this.start.latitude, this.start.longitude],
              
              launchModeAppleMaps: "mapkit"
          
            };
           
            
            this.launchNavigator.navigate([this.selectedCompany.latitude, this.selectedCompany.longitude], options)
                .then(
                    success => alert('Launched navigator'),
                    error => alert('Error launching navigator: ' + error)
            );
    }
Thanks in advance !!

**Comment by venkatan91** [comment]
versions
uk.co.workingedge.phonegap.plugin.launchnavigator  4.1.3
ionic-native/launch-navigator 4.4.2
ios 11.2.5

**Comment by venkatan91** [comment]
Thanks

**Comment by dpa99c** [comment]
Upon investigation, this is simply down to how Apple Maps handles launch intents from the URI or MapKit call used to launch it, and as such this plugin has no control over how the Apple Maps app chooses to handle that intent.

In a nutshell: there's nothing I can do to change the behaviour of Apple Maps.

The [launchModeAppleMaps](https://github.com/dpa99c/phonegap-launch-navigator#apple-maps-launch-method) parameter toggles between using the URI scheme to launch Apple Maps vs the native MapKit class.

[The URI scheme is set](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/LaunchNavigator.m#L248) as described in the [Apple documentation](https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html), as is the [MapKit class set](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/LaunchNavigator.m#L285) according to the documentation.

There are no documented options for either launch method that would cause Apple Maps to launch differently and achieve different UI features as shown in your screenshots.
