### ISSUE TITLE
Disabled apps are treated as available even though the apps cannot be opened.

### ISSUE THREAD

**Issue by iamjoyce** [dpa99c/phonegap-launch-navigator#182]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [x] feature request
- [ ] documentation issue

# Bug report

**Prerequisite:**

No map apps were installed, and default map app (Google map) is disabled.

**Current behavior:**

`this.launchNavigator.navigate(...)`
- Nothing happens; There is no error or message returned in the `Promise` even though the popup did not open.

`this.launchNavigator.availableApps()`
- Even though Google map is disabled, the response returned `google_maps: true`, which isn't exactly true because Google map not available for use.

`this.launchNavigator.isAppAvailable('google_maps')`
- Response is also `true`

**Expected behavior:**

`this.launchNavigator.navigate()` should return something to indicate that map app failed to launch.

`this.launchNavigator.availableApps()` should not return apps that are disabled.

`this.launchNavigator.isAppAvailable('google_maps')` should return `false` since the app is disabled.

**Steps to reproduce:**

1. Disable/ Uninstall all map apps in the phone.
1. Call `this.launchNavigator.navigate()`
	- Nothing happens
1. Call `this.launchNavigator.availableApps()`
	- Map app that was disabled will still be counted as 'available'.

**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- android 6.3.0
- Plugins & versions installed in project (including this plugin)
    - com-sarriaroman-photoviewer 1.1.11 "PhotoViewer"
    - cordova-plugin-actionsheet 2.3.3 "ActionSheet"
    - cordova-plugin-camera 4.0.2 "Camera"
    - cordova-plugin-device 1.1.7 "Device"
    - cordova-plugin-dialogs 2.0.1 "Notification"
    - cordova-plugin-file 6.0.1 "File"
    - cordova-plugin-globalization 1.0.9 "Globalization"
    - cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
    - cordova-plugin-mauron85-background-geolocation 2.3.3 "CDVBackgroundGeolocation"
    - cordova-plugin-network-information 1.3.4 "Network Information"
    - cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
    - cordova-plugin-splashscreen 4.1.0 "Splashscreen"
    - cordova-plugin-statusbar 2.4.1 "StatusBar"
    - cordova-plugin-whitelist 1.3.3 "Whitelist"
    - cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
    - cordova.plugins.diagnostic 3.9.2 "Diagnostic"
    - phonegap-plugin-barcodescanner 7.0.2 "BarcodeScanner"
    - uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.3 "Launch Navigator"
- Dev machine OS and version, e.g.
    - Windows 10
        - Version 1709
        
_Runtime issue_
- Device details
    - Lenovo Vibe S1
- OS details
    - Android 5.0

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - @ionic/cli-utils  : 1.19.1
    - ionic (Ionic CLI) : 3.19.1
- Installed Ionic Native modules and versions
    - _(Feel free to let me know if you still need this)_

**Comment by dpa99c** [comment]
Thanks for reporting. Disabling Google Maps isn't an edge case I'd thought of, but it should be possible to detect if it's been disabled: https://stackoverflow.com/a/14558066/777265

**Comment by iamjoyce** [comment]
Tested and verified that `availableApps()` returns correctly.

Just FYI - If the map_app is enabled while the app is running, the map_app is still counted as not available (i.e. `false`) until the app restarts.
