### ISSUE TITLE
[just a recommand] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [dpa99c/phonegap-launch-navigator#19]
hi @dpa99c 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by dpa99c** [comment]
It already is: https://www.npmjs.com/package/uk.co.workingedge.phonegap.plugin.launchnavigator

**Comment by bau720123** [comment]
thanks @dpa99c
