### ISSUE TITLE
ERROR BUILDING

### ISSUE THREAD

**Issue by sigautomacao** [dpa99c/phonegap-launch-navigator#191]
Every time I install this plugin my ionic does not compile from errors that I can not fix, and when I remove compiles again.

FAILURE:
Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not download okhttp.jar (com.squareup.okhttp3:okhttp:3.10.0)
   > Could not get resource 'https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar'.
         > akamai.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
26 actionable tasks: 4 executed, 22 up-to-date
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not download okhttp.jar (com.squareup.okhttp3:okhttp:3.10.0)
   > Could not get resource 'https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar'.
         > akamai.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

[ERROR] An error occurred while running cordova build android (exit code 1).

**Comment by dpa99c** [comment]
This plugin [depends on](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L50) the OKHTTP library, which it pulls in via Gradle during the Android build process.

For some reason your build environment is failing to fetch the library during the build process.
You can confirm the requested URL exists by visiting:
https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar

You can try building an app in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to rule out a collision with another plugin or an issue which is specific to your project.

**Comment by dpa99c** [comment]
Closed due to no response from OP
