### ISSUE TITLE
Prompt to remember choice only shows the first time, not the subsequent times.

### ISSUE THREAD

**Issue by tala9999** [dpa99c/phonegap-launch-navigator#192]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ x] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
I'm using this launchOptions

```
        let launchOptions = {
          appSelection: {
            rememberChoice: { enabled: "prompt", prompt: { headerText: "Remember this choice?" } }
          }
        };

        launchNavigator.navigate([lat, lng], launchOptions);

```
When users select No at the prompt screen, the prompt will not be shown again so in case users change their mind and want to remember the choice, they have to delete the app (or app settings) to see the prompt again.

**Expected behavior:**
The prompt to remember choice should be shown again so users have chance to remember the choice if they want. This is much more convenient for them.

**Comment by dpa99c** [comment]
If a user answers "No" when asked if they wish their choice to be remembered, it does not make sense for the default behaviour to ask them again every time the choose to navigate - that's just annoying for the user.

However, if you wish to implement that behaviour, you can simply just call [launchnavigator.appSelection.userPrompted.clear()](https://github.com/dpa99c/phonegap-launch-navigator#appselectionuserpromptedclear) every time before calling `navigate()` which will clears the flag which indicates if the user has already been prompted.

**Comment by tala9999** [comment]
Awesome. Thanks for the quick reply.
