### ISSUE TITLE
iOS 12, Xcode Beta 12, ld: 132 duplicate symbols for architecture arm64 (Runs on simulator but not in the device)

### ISSUE THREAD

**Issue by NextiaDev** [dpa99c/phonegap-launch-navigator#199]
**This is the message that I receive in the console:** 

duplicate symbol l115 in:
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(CLSFileManager.o)
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Fabric/iOS/Fabric.framework/Fabric(CLSUserDefaults.o)
duplicate symbol l057 in:
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(CLSSymbolResolver.o)
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Fabric/iOS/Fabric.framework/Fabric(FABAsyncOperation.o)
duplicate symbol l058 in:
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(ANSCleanupFilesOperation.o)
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Fabric/iOS/Fabric.framework/Fabric(FABAsyncOperation.o)
duplicate symbol l076 in:
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(ANSSettings.o)
    /Users/dariobaltierra/Documents/Versiones funcionales/08:08:2018 bug fixing/Siclo-App/SicloApp/Pods/Fabric/iOS/Fabric.framework/Fabric(FABCompoundOperation.o)
ld: 132 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**I have tried all the solutions that I found on internet but anyone works. There's no a lot of information about xcode and iOS 12,**

**Comment by dpa99c** [comment]
The cause of the error is evident in the console output and it has nothing to do with this plugin:
you have both the Fabric and Crashlytics SDKs present in the native project. Fabric includes the Crashlytics classes so you have duplicate classes which is causing your build error. Solution is to remove one of those SDKs.
