### ISSUE TITLE
How to put current location and destination 

### ISSUE THREAD

**Issue by nawanirakshit** [dpa99c/phonegap-launch-navigator#20]
I tried to use your source and destination link but the link is not found.
I want to put navigation between current and source place.
can you suggest me on that
Thank you

**Comment by dpa99c** [comment]
What platform are you having issues with? iOS/Android/Windows? 
And what OS version? e.g. iOS 8.3/Android 4.4.4?

**Comment by nawanirakshit** [comment]
Android all versions (mine lollipop)
I want to navigate from current location to destination

**Comment by dpa99c** [comment]
To use current position as start location, just pass in `null` as start location, e.g. 

    launchnavigator.navigate(
      "London, UK",
      null,
      function(){
          alert("Plugin success");
      },
      function(error){
          alert("Plugin error: "+ error);
      });

See the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) as a reference. Also make sure your country is supported for turn-by-turn navigation by Google Maps.

**Comment by dpa99c** [comment]
Since you've not responded, I'm going to assume you're issue is resolved
