### ISSUE TITLE
 Could not find property 'OKHTTP_VERSION' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@7eeabaf3.

### ISSUE THREAD

**Issue by ndar0430** [dpa99c/phonegap-launch-navigator#200]
hi, i'm having trouble with cordova build, 

it says
 Could not find property 'OKHTTP_VERSION' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@7eeabaf3.

Cordova -v: 6.3.1

**Comment by dpa99c** [comment]
@cayau upgrade to latest Cordova CLI:

    npm install -g cordova@latest

**Comment by mo-debo** [comment]
i have the same issue im using dotnet cordova tool  , not working with me 
please how i solve that.
