### ISSUE TITLE
Feature Request: Careem in the Middle East

### ISSUE THREAD

**Issue by paulincai** [dpa99c/phonegap-launch-navigator#204]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ * ] feature request
- [ ] documentation issue

Integration with Careem in the Middle East: https://www.careem.com/en-ae/cities/

**Comment by dpa99c** [comment]
While Careem appears to provide the [relevant deeplinking documentation](https://developer.careem.com/deepLinking), you need to sign up for a Careem account to access it.

However, when I attempt to sign up for an account, the server responds with a 403 error:

![https___account careem com_sign-up_en_ countrycode](https://user-images.githubusercontent.com/2345062/47511190-99eab500-d871-11e8-9ced-b49d143774a4.png)

If you have an account already, please log in and post the relevant details from the deep linking page here. Without details of the URL scheme, it won't be able to add support for Careem.

**Comment by dpa99c** [comment]
Note: I've contacted Careem to ask if they can fix their sign up form or provide a direct (unrestricted) link to the deep linking documentation.

**Comment by paulincai** [comment]
Hi @dpa99c, I went to Facebook way and got stuck with "invalid phone number". I opened a ticket on their website. Ok ... they are really famous here but this sound ... disappointing. I keep this on my list and will try to get the data from them. I think a I also know some people there.
