### ISSUE TITLE
Issue with adding LaunchNavigator to NgModule providers in Ionic 4

### ISSUE THREAD

**Issue by zharding** [dpa99c/phonegap-launch-navigator#208]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

When adding 'LaunchNavigator' to providers inside NgModule the following error occurs. 
```
[ng] ERROR in src/app/app.module.ts(17,11): error TS2345: Argument of type '{ declarations: (typeof AppComponent)[]; entryComponents: undefined[]; imports: (ModuleWithProvid...' is not assignable to parameter of type 'NgModule'.
[ng]   Types of property 'providers' are incompatible.
[ng]     Type '(typeof SplashScreen | LaunchNavigatorOriginal | { provide: typeof RouteReuseStrategy; useClass: ...' is not assignable to type 'Provider[]'.
[ng]       Type 'typeof SplashScreen | LaunchNavigatorOriginal | { provide: typeof RouteReuseStrategy; useClass: t...' is not assignable to type 'Provider'.
[ng]         Type 'LaunchNavigatorOriginal' is not assignable to type 'Provider'.
[ng]           Type 'LaunchNavigatorOriginal' is not assignable to type 'ClassProvider'.
[ng]             Property 'provide' is missing in type 'LaunchNavigatorOriginal'.
[ng] src/app/pages/dashboard/main/main.page.ts(88,34): error TS2304: Cannot find name 'LaunchNavigator'.
```

**Expected behavior:**
I expect this error not to occur? Following the instructions here [https://beta.ionicframework.com/docs/native/launch-navigator/](url) and [https://github.com/dpa99c/phonegap-launch-navigator](url) Should work fine. I have been migrating an older ionic 3 app to a new fresh ionic 4 app. All worked prior in ionic 4. 

**Steps to reproduce:**

- Start a new ionic app type=angular
- Follow the guide [https://beta.ionicframework.com/docs/native/launch-navigator/](url)
- Add LaunchNavigator to NgModule in providers

**Environment information**

- Cordova CLI version 
	- `8.0.0`
- Cordova platform version
```
Installed platforms:

Available platforms:
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-geolocation 4.0.1 "Geolocation"`
    - `uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"`
- Dev machine OS and version, e.g.
    - Windows 10
        - `1709 (Build 16299.726)`
        
_If using an [Ionic Native Typescript wrapper]() for this plugin:_
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\ZacharyHarding\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.8.6
   @angular-devkit/schematics : 0.8.6
   @angular/cli               : 6.2.6
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   NodeJS : v9.5.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```
- Installed Ionic Native modules and versions
```
+-- @ionic-native/camera@5.0.0-beta.21
+-- @ionic-native/core@5.0.0-beta.21
+-- @ionic-native/geolocation@5.0.0-beta.21
+-- @ionic-native/in-app-browser@5.0.0-beta.21
+-- @ionic-native/launch-navigator@5.0.0-beta.21
+-- @ionic-native/push@5.0.0-beta.21
+-- @ionic-native/splash-screen@5.0.0-beta.21
+-- @ionic-native/status-bar@5.0.0-beta.21
```

**Comment by dpa99c** [comment]
This issue relates to the [Ionic Native Typescript wrapper](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts) for this plugin, which is created and maintained by Ionic. This repo contains only the Launch Navigator Cordova plugin itself, comprised of the native plugin implementation and pure Javascript API.

Therefore the issue should be [raised against Ionic Native](https://github.com/ionic-team/ionic-native/issues) which contains the relevant Typescript code.

**Comment by zharding** [comment]
@dpa99c Ah, makes sense. It is literally a guid issue anyhow. 

Resolution: add `nix` to the import. `import {LaunchNavigator} from '@ionic-native/launch-navigator/ngx';` 

Apparently, they need to update quite a bit. I will attempt to throw my two cents in over there. 

Thank you.

**Comment by Fomare** [comment]
That works for me, but now, I get this error when ionic serve 

> ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at OneSignal.startInit (index.js:79)

>

**Comment by keyurmeandev** [comment]
Facing the same issue here @Fomare

**Comment by dpa99c** [comment]
`OneSignal.startInit` indicates the problem lies with the One Signal plugin.

As documented, this plugin requires a **native mobile platform** (iOS/Android/Windows 10) so will not work in the browser emulation invoked by `ionic serve`

**Comment by keyurmeandev** [comment]
@dpa99c Yes, correct it will not work in browser but it's giving same error after building the apk and checking in the android device.

**Comment by keyurmeandev** [comment]
@dpa99c @Fomare It's done. 

We need to install the right version of launch-navigator according to ionic-native version..

npm i @ionic-native/launch-navigator@4.12.0

This has solved my problem..
