### ISSUE TITLE
When I call the phonegap-launch-navigator service; This takes a long time to open the list of options to open the external map on Android.

### ISSUE THREAD

**Issue by dawerdrew** [dpa99c/phonegap-launch-navigator#210]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

I click on the button to open the navigation with coordinates to open an external map. In iOS works immediately without problems. The problem is in Android. In Android I have installed google maps and Waze, When I click on the button to open the external map, the plugin takes a long time to display the list of options to open the external map, after opening the external map, I return to the app and I click on the button again and the plugin takes more time than the first time to display the list of options to open the external map.

**Expected behavior:**

I hope that in Android when I click on the external map button, the list of map applications is immediately displayed as it is in the case of iOS.

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- 8.1.2 (cordova-lib@8.1.1)
- Cordova platform version
	-   android 7.1.4
	-   ios 4.5.5
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-actionsheet 2.3.3 "ActionSheet"
    - cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
    - cordova-plugin-device 2.0.2 "Device"
    - cordova-plugin-dialogs 2.0.1 "Notification"
    - cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
    - cordova-plugin-facebook4 4.0.0 "Facebook Connect"
    - cordova-plugin-file 6.0.1 "File"
    - cordova-plugin-file-opener2 2.0.19 "File Opener2"
    - cordova-plugin-file-transfer 1.7.1 "File Transfer"
    - cordova-plugin-geolocation 4.0.1 "Geolocation"
    - cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
    - cordova-plugin-googleplus 6.0.0 "Google SignIn"
    - cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
    - cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
    - cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
    - cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
    - cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
    - cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    - cordova-plugin-statusbar 2.4.2 "StatusBar"
    - cordova-plugin-whitelist 1.3.3 "Whitelist"
    - cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
    - es6-promise-plugin 4.2.2 "Promise"
    - onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
    - uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	Mac OS X
        - ProductVersion:	10.13.6
        - BuildVersion:	17G65
        
_Runtime issue_
- Device details
    - _e.g. iPhone 7, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - v8.12.0
- Gradle version
	- 4.1			4.6			vcsWorkingDirs
           4.10.2			                buildOutputCleanup
- Target Android SDK version
	- 27

**Related code:**

```
    abrirMapa(myLocation){
      let options: LaunchNavigatorOptions = {
        start: myLocation
        // app: this.launchnavigator.APP.WAZE
      };
      var destination = this.lat + ',' + this.lng;
        console.log('abriendo mapas');
      this.launchNavigator.navigate(destination, options)
      .then(success => {
        console.log('Launched ')
      },error => {
        console.log('Error launching navigator', error);
      }
      );
    }
```

**Other information:**

**Comment by dpa99c** [comment]
I've regression tested the [Ionic 3 Example app](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic3Example) using `cordova-android@7.1.4` and running on a Nexus 6P running Android 8.1. As you can see from [this screen capture](http://ge.tt/3446Ajt2), the plugin responds almost immediately to display a list of available navigation apps on the device.

Please try building and running an app from the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to eliminate the possibility that some other element in your app is responsible for making the plugin slow to respond.

**Comment by dpa99c** [comment]
Closed due to no response
