### ISSUE TITLE
Can not build for iOS

### ISSUE THREAD

**Issue by xyboox** [dpa99c/phonegap-launch-navigator#217]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Error on cordova build ios: 
`duplicate symbol _LNEmptyCoord in:
    /Users/xxxxxx/Library/Developer/Xcode/DerivedData/ProjName-arfcoawdbkmcnjdnmyhvczuakgpn/Build/Intermediates.noindex/ArchiveIntermediates/ProjName/IntermediateBuildFilesPath/ProjName.build/Debug-iphoneos/ProjName.build/Objects-normal/arm64/LaunchNavigatorPlugin.o
    /Users/xxxxxx/Library/Developer/Xcode/DerivedData/ProjName-arfcoawdbkmcnjdnmyhvczuakgpn/Build/Intermediates.noindex/ArchiveIntermediates/ProjName/IntermediateBuildFilesPath/ProjName.build/Debug-iphoneos/ProjName.build/Objects-normal/arm64/LN_LaunchNavigator.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I've tried with a blank new Ionic ( v3 ) project and only added this plugin. Same behaviour: can not build ios with same error as above.

**Environment information**

- Cordova CLI version 
	- `8.1.2 (cordova-lib@8.1.1)`
- Cordova platform version
	- `ios 5.0.0` also tested with `ios 4.5.5`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-actionsheet 2.3.3 "ActionSheet"`
    - `cordova-plugin-device 2.0.2 "Device"`
    - `cordova-plugin-dialogs 2.0.1 "Notification"`
    - `cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"`
    - `cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"`
    - `cordova-plugin-splashscreen 5.0.2 "Splashscreen"`
    - `cordova-plugin-statusbar 2.4.2 "StatusBar"`
    - `cordova-plugin-whitelist 1.3.3 "Whitelist"`
    - `uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.3 "Launch Navigator"`

- Dev machine OS and version, e.g.
    - OSX
        - `ProductName:	Mac OS X`
        - `ProductVersion:	10.14.3`
        - `BuildVersion:	18D109`
        

_Runtime issue_
- Device details
    - any iOS device

_iOS build issue:_
- Node JS version
    - `v10.15.0`
- XCode version
   - `Version 10.1 (10B61)`

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - Ionic:

  ` ionic (Ionic CLI)  : 4.10.2 (/usr/local/lib/node_modules/ionic)`
   `Ionic Framework    : ionic-angular 3.9.3`
   `@ionic/app-scripts : 3.2.1`

    -  Cordova:

  `cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)`
  `Cordova Platforms     : ios 5.0.0`
   `Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)`

    - System:

   `Android SDK Tools : 26.1.1 (/Users/xxxxxx/Library/Android/sdk)`
  ` ios-deploy        : 1.9.4`
   `ios-sim           : 7.0.0`
   `NodeJS            : v10.15.0 (/usr/local/Cellar/node@10/10.15.0/bin/node)`
  ` npm               : 6.4.1`
   `OS                : macOS Mojave`
   `Xcode             : Xcode 10.1 Build version 10B61`

**Comment by dpa99c** [comment]
This is an incompatibility with the newly released `cordova-ios@5` - it builds successfully with `cordova-ios@4`, but will need investigating/fixing for `@5`

**Comment by dpa99c** [comment]
Fix published to npm in v5.0.4

**Comment by xyboox** [comment]
Thanks, seems to be working!
Great work!

Ciprian D.



From: Dave Alden <notifications@github.com> <notifications@github.com>
Reply: dpa99c/phonegap-launch-navigator
<reply@reply.github.com>
<reply@reply.github.com>
Date: 11 February 2019 at 23:18:59
To: dpa99c/phonegap-launch-navigator
<phonegap-launch-navigator@noreply.github.com>
<phonegap-launch-navigator@noreply.github.com>
Cc: Ciprian Dragoste <xyboox@gmail.com> <xyboox@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [dpa99c/phonegap-launch-navigator] Can not build for iOS
(#217)

Fix published to npm in v5.0.4

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dpa99c/phonegap-launch-navigator/issues/217#issuecomment-462498343>,
or mute the thread
