### ISSUE TITLE
Android build error for cordova platform@6.5.0

### ISSUE THREAD

**Issue by YaroslavG** [dpa99c/phonegap-launch-navigator#218]
Hi all, a few days ago I encountered an error when building my android project when this plugin is added:
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
when I removed this plugin the android build compiles successfully

**Comment by dpa99c** [comment]
This is fixed by 99f43a2f62317f9dc8e6c87906d4dd3048bcd41f which was released in v5.0.2.

Please update to the latest version.

**Comment by dedd1993** [comment]
Im using cordova 6.4 wich support 3.2.2 plugin version... For proyect specifications I can´t upgrade cordova, so Im trying the following (without success):

`cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator --variable GOOGLE_API_KEY_FOR_ANDROID="{your_api_key}" --variable OKHTTP_VERSION=3.12.0`

Help please :(

**Comment by YaroslavG** [comment]
You do not confuse the version of cordova and cordova-android? in my case, I have been successfully updated cordova to the version 7.1 and it helped me.
