### ISSUE TITLE
exclude application from routing application list 

### ISSUE THREAD

**Issue by ansarikhurshid786** [dpa99c/phonegap-launch-navigator#219]
is there any option to exclude application from suggested application for routing list?

**Comment by dpa99c** [comment]
The out-of-the-box UI included with the plugin provides basic functionality for a quickstart that follows the most common use cases.

However, if you want to create bespoke UI behaviour such as excluding available navigation apps from the list presented to the user, you can create your own UI to manage this using the plugin's API functions such as [availableApps()](https://github.com/dpa99c/phonegap-launch-navigator#availableapps) to return a list of the available supported navigation apps which are installed on the current device and then filter that list before presenting to the user.

The [AdvancedExample](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/AdvancedExample) app in the [example repo](https://github.com/dpa99c/phonegap-launch-navigator-example) demonstrates how to create a custom UI using the plugin API functions.
