### ISSUE TITLE
Error launchnavigator.app 

### ISSUE THREAD

**Issue by ansarikhurshid786** [dpa99c/phonegap-launch-navigator#220]
I am trying to restrict only two application for user selection but i am getting error launchnavigator.app  - app is not defined.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/phonegap-launch-navigator#app), the constants are in the `launchnavigator.APP` global JS namespace (case-sensitive), for example `launchnavigator.APP.GOOGLE_MAPS`
