### ISSUE TITLE
typo in .d.ts

### ISSUE THREAD

**Issue by tuif** [dpa99c/phonegap-launch-navigator#221]
Hello,
There is a small mistake in .d.ts:
    enableDebug: (
        enabled: boolean,
        successCallback: (any) => void,
        errorCallback?: (error: string) => void
    ) => void;

successCallback should be the type of (result: any) => void, otherwise typescript compiler would failed if noImplicitAny is set true in tsconfig.json.

**Comment by catalinmitrofan** [comment]
I encountered the same issue.  Is there any plan, when the typo would get fixed?

**Comment by dpa99c** [comment]
Fixed by #229
