### ISSUE TITLE
GOOGLE_API_KEY should be optional

### ISSUE THREAD

**Issue by Arnaud49** [dpa99c/phonegap-launch-navigator#222]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

# Feature request

First of all, thank you for developing this plugin on your free time.
I'm using it in my app and its very useful.

- A descriptive title 
GOOGLE_API_KEY should be optional

- A description of the problem you're trying to solve, including why you think this is a problem
I just remove google maps from my app and i'm now using my own OSM tiles server. I don't want to use my GOOGLE_API_KEY anymore. In fact i'm using your plugin only with lat and lng, so I don't even need it.

- An overview of the suggested solution
Do not reject the installation without the KEY, and if using the plugin on android with an address put an error message to say you need the GOOGLE KEY to continue.

- Use case: why should this be implemented?
You shouldn't reject the installation because of some google key missing for a feature of your plugin some people don't use ?
Well at least it's my opinion, no offense here.

- If the feature changes current behavior, reasons why your solution is better
A lot of people don't want to do anything with google, you will loosing some people because of that, still in my opinion.

**Comment by dpa99c** [comment]
If you don't want to use it, just specify a blank value 🙄 

    cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator --variable GOOGLE_API_KEY_FOR_ANDROID=""
