### ISSUE TITLE
Error when injecting in ionic 3

### ISSUE THREAD

**Issue by SylvanoTombo** [dpa99c/phonegap-launch-navigator#225]
Can't resolve all parameters for [object Object], [object Object], [object Object], [object Object], ?)

**Comment by dpa99c** [comment]
This is insufficient information to open an issue - please complete the issue template to provide the required information.

Before doing so please try building and running the [Ionic 3 example app](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic3Example) from the [example project repo](https://github.com/dpa99c/phonegap-launch-navigator-example/) as a working reference to eliminate the cause of the issue as being within your own project.

**Comment by SylvanoTombo** [comment]
Thank for your response, it's about package incompatibility in my project.
