### ISSUE TITLE
Google maps not loading route (iPhone)

### ISSUE THREAD

**Issue by capc0** [dpa99c/phonegap-launch-navigator#227]
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Launching google maps on iOS (iPhone) will result in a endless loading spinner. The gps coordinates are shown correctly but the location is never resolved. When changing to e.g. 'walking' and back to 'driving', the route gets loaded properly. Same code on iPad works fine.

**Expected behavior:**

Google maps should load the route instantly.

**Steps to reproduce:**

**Make sure to have google maps closed.**
Launch via this plugin by latitude and longitude coordinates on iPhone (iOS 13)

**Environment information**

- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- `ios 5.0.1`
- Plugins & versions installed in project (including this plugin)
    - `uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4`
- Dev machine OS and version, e.g.
    - OSX
        - `10.14.6`
        
_Runtime issue_
- Device details
    - iPhone 6s
- OS details
    - iOs 13.1.3

**Comment by dpa99c** [comment]
This plugin has no control over the internal behaviour of the Google Maps app - it simply invokes and launches it via its custom URL scheme. Therefore there's nothing that could be done by this plugin to affect whether the spinner appears or the location resolves.

**Comment by dpeacock** [comment]
@capc0 I'm experiencing the same issue but agree with @dpa99c that this isn't a plug-in issue.  I've posted an issue to the Google Maps issue tracker here: https://issuetracker.google.com/issues/144150442

**Comment by capc0** [comment]
@dpeacock Btw my workaround was to explicity pass a starting position. Requested the current position first and then forwarded it to this plugin

**Comment by dpeacock** [comment]
@capc0 thanks, that's a decent workaround for now :)
