### ISSUE TITLE
Feature Request: Mode parameter for google map

### ISSUE THREAD

**Issue by heshan-nibaya** [dpa99c/phonegap-launch-navigator#23]
Hi, I was wondering if you have any plan to integrate method of transportation (mode) for your plugin.

**Comment by dpa99c** [comment]
Added to the [roadmap](https://github.com/dpa99c/phonegap-launch-navigator/wiki/Roadmap). When I get a bit of time, I'll add it.

**Comment by heshan-nibaya** [comment]
Hi Dave, Nice to hear looking forward to it.

**Comment by dpa99c** [comment]
Latest version of the plugin (2.9.0) now enables transportation mode to be specified.

**Comment by heshan-nibaya** [comment]
Hi dave, Great! job.
