### ISSUE TITLE
Detect available apps (Ionic cordova app)

### ISSUE THREAD

**Issue by petrot** [dpa99c/phonegap-launch-navigator#230]
# Documentation issue
What is the exact way to list the available apps on the device? For me, there wasn't any app on the list on iOS (and just the Apple maps worked), until I wrote the following lines to the (Ionic) config.xml:

```
<edit-config file="*-Info.plist" mode="merge" target="LSApplicationQueriesSchemes">
            <array>
                <string>comgooglemaps</string>
                <string>waze</string>
                <string>uber</string>
            </array>
        </edit-config>
```

After this config I could choose from my installed apps (Google maps, Waze, Apple maps)

**Comment by dpa99c** [comment]
This plugin [includes all relevant iOS URL schemes](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L102) into the `-Info.plist` at plugin installation time.

You can verify this by building and running one of the apps in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example).

As to why this configuration wasn't added in your particular case, I can only speculate, however it's possible that a conflict with another plugin or error during the build process caused Cordova to fail to add the entries to the `-Info.plist`
