### ISSUE TITLE
Is it possible to open maps without giving a starting point?

### ISSUE THREAD

**Issue by blasco** [dpa99c/phonegap-launch-navigator#232]
I would like to open google maps but only with a provided location and without a starting point. Is this somehow possible? Thank you for the support and for the outstanding plugin.

**Comment by dpa99c** [comment]
This is out-of-scope for this plugin which is only intended to provide A-to-B route navigation via 3rd party navigation apps. While Google Maps supports launching with only a single location to provide a map view, other navigation apps supported by this plugin do not.
