### ISSUE TITLE
launchNavigator.LAUNCH_MODE property not found

### ISSUE THREAD

**Issue by SwellingtonSoares** [dpa99c/phonegap-launch-navigator#233]
When you use this.launchNavigator.LAUNCH_MODE.TURN_BY_TURN
Says that the LAUNCH_MODE property does not exist.

Steps for reproduction:

make an interface as it is.

let options: LaunchNavigatorOptions = {
        start: [
          this.coordenada_professional.latitude,
          this.coordenada_professional.longitude
        ],
        app: app,
        transportMode: this.launchNavigator.TRANSPORT_MODE.DRIVING,
        launchModeGoogleMaps: this.launchNavigator.LAUNCH_MODE.TURN_BY_TURN,
        launchModeAppleMaps: this.launchNavigator.LAUNCH_MODE.URI_SCHEME

      };

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by jedskie** [comment]
Hi, did you fix this? I'm encountering the same problem. LAUNCH_MODE not recognize
