### ISSUE TITLE
Cancelled error

### ISSUE THREAD

**Issue by yosikal** [dpa99c/phonegap-launch-navigator#236]
I'm receiving multiple reports from users that navigation doesn't work as expected. When checking Sentry logs I see that there is common error in which the launchnavigator.navigate returns to the error callback passing to it "cancelled" as the error message. Any idea?

**Comment by dpa99c** [comment]
Sorry but there is insufficient information here to determine if there is an issue or investigate it.

The "cancelled" entry in the logs is likely to arise from [this line](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/common.js#L587) which is invoked when the user presses the Cancel button (or taps the background mask) on the actionsheet which is part of the default plugin UI and cancels the actionsheet without invoking a navigation app. Therefore this is likely to be a red herring and not the cause of your users' issues. I suggest contacting the affect users to obtain more information.
