### ISSUE TITLE
undefined 

### ISSUE THREAD

**Issue by mo-debo** [dpa99c/phonegap-launch-navigator#240]
i was use old version it was working fine , when i update to latest one always "undefined"

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
This is insufficient information to determine whether an issue exists.

Please build and run the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to determine if the issue can be reproduced in a known codebase and to rule out causes in your own code.
If the issue can be reproduced, please complete the issue template in full including detailed steps how to reproduce the issue and an exact description of where the error is occurring.
