### ISSUE TITLE
 undefined after upgrade from v 4.2.0 to 5.4.0

### ISSUE THREAD

**Issue by mo-debo** [dpa99c/phonegap-launch-navigator#241]
this plugin already was working before , with version 4.2.0 after update it didn't install 
when i call it all time give me undefined . please Help me fix this

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	-   6.3.1
- Cordova platform version
	- android
- Plugins & versions installed in project (including this plugin)
    https://github.com/dpa99c/phonegap-launch-navigator.git latest on

        
_Runtime issue_
- Device details
    redmi note 7
- OS details
     Android 9.0	
	
_Android build issue:_	
- Node JS version
    - 12.14.0
- Gradle version
	-2.13
 AndroidSDK\25
 dk1.8.0_231
	
_ 
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
> Cordova CLI v6.3.1

Your Cordova CLI is too old - please update to latest Cordova CLI v9.0.0 and `cordova-android@8.1.0` and retest. 
Please build and run the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) as a working example.
