### ISSUE TITLE
A problem occurred evaluating project ':app'. > Could not get unknown property 'OKHTTP_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by mukkulsingh** [dpa99c/phonegap-launch-navigator#243]
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'OKHTTP_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[ERROR] An error occurred while running subprocess cordova.
        
        cordova run android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.

Ionic:

   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.16.1 
   npm    : 6.13.4
   OS     : Linux 4.15

**Comment by dpa99c** [comment]
> Cordova Platforms : android 7.0.0

`cordova-android@7.0.0` is too old and doesn't support plugin variables. Please update to the latest version.

**Comment by mukkulsingh** [comment]
> > Cordova Platforms : android 7.0.0
> 
> `cordova-android@7.0.0` is too old and doesn't support plugin variables. Please update to the latest version.

how to update it?
cause npm update -g cordova updates the cordova CLI not the cordove-android

**Comment by dpa99c** [comment]
`cordova platform rm android && cordova platform add android@latest`

**Comment by mukkulsingh** [comment]
> `cordova platform rm android && cordova platform add android@latest`

Thank you
