### ISSUE TITLE
when "preferGoogleMaps" set to true，If Google Maps is not available, it "will not" fall back to Apple Maps

### ISSUE THREAD

**Issue by bau720123** [dpa99c/phonegap-launch-navigator#25]
hi @dpa99c 
I am using Cordova 5.1.1 + all latest official core plugin + your plugin 2.9.0

If Google Maps is available (installed)，when "preferGoogleMaps" set to true，it really open the googleMap instead of Apple Maps
but...
If Google Maps is not available (not installed)，when "preferGoogleMaps" still set to true，it do nothing (nothing means that there is no any further action，just "nothing")

**Comment by dpa99c** [comment]
Thanks for reporting this bug, I've tracked it down and fixed it in v2.9.2 of the plugin

**Comment by bau720123** [comment]
thanks for @dpa99c reply
thanks you again
really awesome plugin !!

**Comment by dpa99c** [comment]
I'm glad you find it useful!
If you have any suggestions or feature requests, please let me know.
Although I'm using this plugin in my own apps, it's good to know how other people are using it and what they would also find useful.

**Comment by bau720123** [comment]
I'm going to cry! @dpa99c 
I must said it again
it really useful !!!

**Comment by bau720123** [comment]
problem solved in 2.9.5 version
thanks @dpa99c
