### ISSUE TITLE
Launch Navigator set coordinate but wont open google maps

### ISSUE THREAD

**Issue by alexisqc92** [dpa99c/phonegap-launch-navigator#252]
So I have use this plugin with ionic5 and angular 9, I was able to set the destination in google maps, but it wont change apps between my app to google maps. Probably a bug with the version. 

` const dest = [lat, lng];

      this.launchNavigator.navigate(dest)
      .then( success => {
        console.log('NAVEGANDO');
        console.log(success);
      }, e => {
        console.log('algo salio mal');
        console.log(e);
      }
      );`

**Comment by dpa99c** [comment]
This is not sufficient information to diagnose an issue.
Please try to replicate the issue in one of the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) apps to rule out bugs in your own codebase.
If you're able to replicate the issue in that known codebase, please open a new issue and fully complete the issue template to provide all the required information.
