### ISSUE TITLE
Issues with Xcode 12.3 / Redefinition of enumerator & Expected identifier or '('

### ISSUE THREAD

**Issue by patrickbussmann** [dpa99c/phonegap-launch-navigator#258]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/phonegap-launch-navigator#reporting-issues)
- [X] I confirm this is a suspected bug or issue that will affect other users
- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) or provided the necessary information to reproduce the issue.
- [X] I have read [the documentation](https://github.com/dpa99c/phonegap-launch-navigator) thoroughly and it does not help solve my issue.
- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

```
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:15:5: redefinition of enumerator 'NotReachable'
    NotReachable = 0,
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:16:5: redefinition of enumerator 'ReachableViaWiFi'
    ReachableViaWiFi,
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:17:5: redefinition of enumerator 'ReachableViaWWAN'
    ReachableViaWWAN
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:24:18: expected identifier or '('
extern NSString *kReachabilityChangedNotification;
```

_iOS build issue:_
- Node JS version
    - 14
- XCode version
    - Xcode 12.3 (Build version 12C33)

There was an issue in the past with the redefinition thing.
#248 #251

When I have time I'll fix this issue here, too.

**Comment by zieemer** [comment]
Hi
Any ideas when fix might be ready ?

**Comment by blhylton** [comment]
Had to work through this in short order for a quick turnaround project. Created a PR with the updates.

**Comment by j3gb3rt** [comment]
Our team is facing this issue also. @blhylton Thanks for the patch! Looking forward to this being released

**Comment by vivek365** [comment]
I am facing the same issue. Is there any chance to release a new version in near future with this fix?

**Comment by dpa99c** [comment]
The current master branch has been released to npm as `uk.co.workingedge.phonegap.plugin.launchnavigator@5.0.6`

**Comment by vivek365** [comment]
thanks @dpa99c
