### ISSUE TITLE
Unsupported apps displayed, but do not launch

### ISSUE THREAD

**Issue by Whit11** [dpa99c/phonegap-launch-navigator#264]
Apologies if this has already been covered, or I have missed it in the plugin information, but I have looked and haven't been able to find anything that covers my exact issue.

The app is installed on an Android device, and the plugin has been installed with the default settings of launchnavigator.APP.USER_SELECT.

The issue I'm experiencing is the plugin detects and displays a number of apps which aren't in the plugins supported list, but many do not actually load.

In this example I have the following apps installed on the device; Bolt, Google Maps, Google Earth, Uber, Waze and Zoom. Google Maps, Uber and Waze all launch when selected, but Bolt, Google Earth and Zoom do not.

My question is whether there is a configuation that either allows all of these apps to actually launch, or if specific apps can be disabled? Having installed apps being displayed that cannot launch is misleading for the user, so would be great if this could be looked into please.

Many thanks

**Comment by dpa99c** [comment]
By default on Android, in addition to the list of explicitly support apps, this plugin includes the list of apps installed on the device which have registered to support the [`geo:` URI scheme](https://developer.android.com/guide/components/intents-common#Maps). This is a global URI scheme for which apps can register their support so they may be included in lists when the user is offered a choice of which app to use to open a location.
While some apps make good use of this, others simply register themselves for all available URI schemes to ensure their app appears in as many lists as possible.

If you don't wish apps which have registered to support the `geo:` URI scheme to appear in the list of available navigation apps, you should explicitly specify the list of apps you wish to display using the `apps` option to specify a list of [app name constants](https://github.com/dpa99c/phonegap-launch-navigator#app).
