### ISSUE TITLE
General Question: Can this plugin open google route maps?

### ISSUE THREAD

**Issue by rolinger** [dpa99c/phonegap-launch-navigator#265]
Hi Dave,

I have been wrestling with getting consistent results trying to open maps and am contemplating trashing all my code in favor of this plugin - but one of the big items I need is to be able to force using Chrome/Safari to open a google route map.

Example route maps are like the following, open in a desktop browser these links work fine, but open in Google Maps app causes them to get messed up - we need to force them to the browser:
1.  https://goo.gl/maps/FyKud884jbVqSNfcA
2.  https://goo.gl/maps/pLCXUfRLVZKMtV5P6 

These route maps are created using google.com/maps on a desktop - then you can send the links to devices or post in webpages or (in my case) in apps.  

Simply using `cordova inAppBrowser` is not reliable because google and iOS see its a map link and either 1) asks the user to open in browser or Maps app - if the user selects Maps then it breaks (see below)  or 2) if use has already defaulted to the Maps app it just auto-opens in the Maps app.

But I need it to open in chrome/safari - or the actual default browser.  We have found that Google Maps doesn't truly honor the route map and garbles it up or shortens it because some of the route paths overlap each other (and then Google Maps trys to find the shortest path causing intentional routes to get truncated)

Could your plugin allow us to force the default browser for these types of route map links?

**Comment by dpa99c** [comment]
This plugin is specifically intended for A>B navigation not route planning so this is beyond scope
