### ISSUE TITLE
Ionic 5 build error

### ISSUE THREAD

**Issue by Evanzsnr** [dpa99c/phonegap-launch-navigator#269]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/phonegap-launch-navigator#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/Evanzsnr/Launch-Navigator) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/phonegap-launch-navigator) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
I added this plugin to my project but when I tried to build my project, the build failed with the error below. I then created a blank project to reproduce the issue, added this plugin successfully as described in the docs, attempted to build and the build still failed with the same error. What could be the issue causing this?
```
FAILURE: 23 actionable tasks: 23 executed
Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  E:\Projects\navigator\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:30: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
E:\Projects\navigator\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  E:\Projects\navigator\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:30: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```
 

**Expected behavior:**
The app is expected to build and run successfully without any errors.

**Steps to reproduce:**
- Create a blank ionic app.
- Install this plugin using `cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator --variable GOOGLE_API_KEY_FOR_ANDROID="{my_api_key}` and `npm install @ionic-native/launch-navigator`
- Build the project using `ionic cordova build android --prod`

**Environment information**
- Cordova CLI version 
	- `10.0.0`
- Cordova platform version
```
Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0
```
- Plugins & versions installed in project (including this plugin)
```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.6 "Launch Navigator"
```
- Dev machine OS and version.
    - Windows 10
        - `Version 20H2 (OS Build 19042.1165)`
	
_Android build issue:_	
- Node JS version
    - `v14.16.1`
- Gradle version
	- `4.10.3/  7.0/  buildOutputCleanup/  checksums/  configuration-cache/  vcs-1/`
- Target Android SDK version
	- `29`

**Comment by timmyomahony** [comment]
Did you find a solution to this? I'm encountering it also.

**Comment by dpa99c** [comment]
You need to update to `cordova-android@10+` and target SDK API 30+
Latest is `cordova-android@11` which targets API 32.

**Comment by timmyomahony** [comment]
Thanks for the quick follow-up. That fixed it.
