### ISSUE TITLE
Vue Support?

### ISSUE THREAD

**Issue by sbellver** [dpa99c/phonegap-launch-navigator#274]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/phonegap-launch-navigator#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/phonegap-launch-navigator) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

I install the plugin in my current ionic 6 app (Vue)

```
npm install @awesome-cordova-plugins/launch-navigator
npm install @awesome-cordova-plugins/core
```

Then I have an error in console:

```
[vue-cli-service] Module not found: Error: Can't resolve '@angular/core' in '/.../node_modules/@awesome-cordova-plugins/launch-navigator/ngx'
```

**Expected behavior:**

Can use it in ionic with Vue, as we use it with Angular

**Comment by GrRivero** [comment]
@sbellver Did you get a solution or what library did you use?

**Comment by sbellver** [comment]
Finally we use a link instead. Works on PWA and in Capacitor

`actionLinks.push({
        text: 'Google Maps',
        icon: mapOutline,
        handler: () => {
          window.open("https://www.google.com/maps/search/?api=1&query="+destination)
        }
      })

      actionLinks.push({
        text: 'Waze',
        icon: carSportOutline,
        handler: () => {
          window.open("https://waze.com/ul?ll="+destination+"&navigate=yes&z=10");
        }
      });`

If mobile have the apps installed, it open it directly

**Comment by dpa99c** [comment]
This plugin doesn't depend on Angular is has [no dependencies](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/package.json).

However you installed it indirectly via the `@awesome-cordova-plugins` bundle.
The name of this package on npm is `uk.co.workingedge.phonegap.plugin.launchnavigator`
