### ISSUE TITLE
Cannot read properties of undefined (reading 'actionsheet')

### ISSUE THREAD

**Issue by hitmacreed** [dpa99c/phonegap-launch-navigator#275]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/phonegap-launch-navigator#reporting-issues)

- [x ] I confirm this is a suspected bug or issue that will affect other users

- [ x] I have read [the documentation](https://github.com/dpa99c/phonegap-launch-navigator) thoroughly and it does not help solve my issue.

- [x ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
`Msg: Unhandled Promise rejection: Cannot read properties of undefined (reading 'actionsheet') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'actionsheet') TypeError: Cannot read properties of undefined (reading 'actionsheet')`

**Expected behavior:**
Launch the navigator

**Steps to reproduce:**
```
import { LaunchNavigator, LaunchNavigatorOptions } from '@awesome-cordova-plugins/launch-navigator/ngx';

constructor(private launchNavigator: LaunchNavigator) { }


let options: LaunchNavigatorOptions = {
  start: 'London, ON',
  app: LaunchNavigator.APPS.UBER
}

this.launchNavigator.navigate('Toronto, ON', options)
  .then(
    success => console.log('Launched navigator'),
    error => console.log('Error launching navigator', error)
  );
```

**Screenshots**
<img width="1404" alt="Screenshot 2022-07-22 at 10 36 10" src="https://user-images.githubusercontent.com/17566079/180411241-f6bfd759-8cc5-400e-aff1-f2388afcd0d6.png">

**Environment information**
Capacitor
        
_Runtime issue_
- Device details
    - Xiaomi Redmi note 9
- OS details
    - Android 11

**Comment by dpa99c** [comment]
This plugin [depends on](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L35) `cordova-plugin-actionsheet` which appears to be missing from your project.

Please use the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to validate plugin functionality before reporting bugs to eliminate problems that are specific to your project.

If you are able to reproduce a bug in the known codebase of the example project, please provide the list of steps required to reproduce it.

**Comment by hitmacreed** [comment]
Hi thanks for the answer, 
this fixed the problem

```
npm i  cordova-plugin-dialogs
npm install @awesome-cordova-plugins/dialogs 

npm i cordova-plugin-actionsheet
$ npm install @awesome-cordova-plugins/action-sheet 

ionic cap sync
```
