### ISSUE TITLE
Why the app need "android.permission.REQUEST_INSTALL_PACKAGES"

### ISSUE THREAD

**Issue by stefanofinetti** [dpa99c/phonegap-launch-navigator#277]
Hello!

I just discovered, because Google rejected the pubblication of an app, that Launch navigator requests for the permission "android.permission.REQUEST_INSTALL_PACKAGES" which is a highly sensitive permission.

Is there any particular reason why the plugin request that feature? 
This is a big issue with google play store right now.

Many thanks in advance

**Comment by dpa99c** [comment]
This plugin does not request `REQUEST_INSTALL_PACKAGES` permission. 
The only Android permission it specifies is `ACCESS_NETWORK_STATE` as can be seen in the [plugin.xml](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L57)

**Comment by stefanofinetti** [comment]
You're right and I'm truly sorry, I was misleaded by the way Capacitor creates the AndroidManifest.xml intermediates. 
It is the file opener plugin that has that wrong permisison, not yours. Again, I'm sorry.
