### ISSUE TITLE
NSInvalidArgumentException in iOS

### ISSUE THREAD

**Issue by Inferner** [dpa99c/phonegap-launch-navigator#28]
I am getting this error in IOS(8.0.2) while trying to launch the plugin . Is this a plugin issue?

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
0x2684df87 0x33e70c77 0x26769ad1 0x26773ae1 0x168601 0x166d07 0xf2925 0xf21af 0xf314b 0x2755c3cf 0x26814807 0x26813c1b 0x26812299 0x2675fdb1 0x2675fbc3 0x2dac4051 0x29d2ba31 0xf82cb 0x3440caaf)
NSException
Process 682 stopped
* thread #1: tid = 0x4be0, 0x344d1dfc libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x344d1dfc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill + 8:
-> 0x344d1dfc:  blo    0x344d1e14                ; __pthread_kill + 32
   0x344d1e00:  ldr    r12, [pc, #4]             ; __pthread_kill + 24
   0x344d1e04:  ldr    r12, [pc, r12]
   0x344d1e08:  b      0x344d1e10                ; __pthread_kill + 28

My js code is
var pickup = this.destination_lat+','+this.destination_long;
var dest = this.pickup_lat+','+this.pickup_long;
launchnavigator.navigate(
			  dest,
			  start,
			  function(){
				 // alert("Plugin success");
			  },
			  function(error){
				  alert("Maps error: "+ error);
			  });

**Comment by dpa99c** [comment]
From your code, it looks like you're passing the destination co-ordinates as a string instead of an array.

The current version of the plugin does not perform input validation to check if the format of co-ordinates is correct, so if an invalid co-ordinate is passed to the plugin, it may cause the issue you are seeing. 

Try changing your code as follows:

    var dest = [this.pickup_lat, this.pickup_long];

Destination parameter documentation:

    /* @param {Mixed} destination (required) - destination location to use for navigation.
     * Either: 
     * - a {String} containing the place name. e.g. "London"
     * - an {Array}, where the first element is the latitude and the second element is a longitude, as decimal numbers. e.g. [50.1, -4.0]
     */

**Comment by Inferner** [comment]
That was it. Thanks a bunch ! Missed the docs as usual.

Just letting you know this code doesn't seem to work.The above error is shown. So place name is also supposed to be an array of sring?

launchnavigator.navigate(
			   "London, UK",
  				"Manchester, UK",
			  function(){
				 // alert("Plugin success");
			  },
			  function(error){
				  alert("Maps error: "+ error);
			  },
			  {
				preferGoogleMaps: true,
				transportMode: "transit",
				enableDebug: true,
				disableAutoGeolocation: true
			});
