### ISSUE TITLE
Missing MapsActivity on Android

### ISSUE THREAD

**Issue by TheDevKnight** [dpa99c/phonegap-launch-navigator#29]
Hi,
i use visual studio 2015 tools for apache cordova (cordova 5.1.1). 
When i launch the navigator... 

           launchnavigator.navigate(
                "Berlin",
                null,
                function() {
                    console.log("success");
                }.bind(this),
                function (error) {
                    console.log(error);
                }.bind(this),
                {
                    disableAutoGeolocation: true,
                    transportMode: "walking"
                }
            );

under android ive got the following error.

Unable to find explicit activity class {com.google.android.apps.maps/com.google.android.maps.MapsActivity}; have you declared this activity in your AndroidManifest.xml?

What must i do? I could run the same code under windows phone (universal) and it works.

Thanks & Regards!

**Comment by dpa99c** [comment]
Hi, are testing using a Android Emulato  rather than a physical device?
That error message indicates Google Maps isn't installed. It's bundled as a system app with most Android ROMs, but not with emulators.

**Comment by TheDevKnight** [comment]
Hi, i execute my app only on the emulator. Thanks for the hint. I will try it on a physical device.

Great work! Cool plugin 😉

Regards
________________________________
Von: Dave Alden<mailto:notifications@github.com>
Gesendet: ‎11.‎09.‎2015 22:13
An: dpa99c/phonegap-launch-navigator<mailto:phonegap-launch-navigator@noreply.github.com>
Cc: TheDevKnight<mailto:henry.ritter@outlook.com>
Betreff: Re: [phonegap-launch-navigator] Missing MapsActivity on Android (#29)

Hi, are testing using a Android Emulato  rather than a physical device?
That error message indicates Google Maps isn't installed. It's bundled as a system app with most Android ROMs, but not with emulators.

---
