### ISSUE TITLE
How can i provide source and destination 

### ISSUE THREAD

**Issue by ullasmohan** [dpa99c/phonegap-launch-navigator#3]
Hi... your plugin seems option to provide destination. 
How can i provide Source and Destination from my app to Google map App for getting the direction.
please guide me.

**Comment by dpa99c** [comment]
This plugin was intended for "route navigation", so only the destination is necessary - to navigate you will always be going from your current location to a destination, in which cause Source is unnecessary. 

What you require is "route planning" functionality, where both the Source and Destination are specified, and this plugin currently doesn't support that.

If your target platform is iOS, this can be done with pure Javascript - [see the iOS plugin source](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/ios/launchnavigator.js)
You'd just need something like `window.location = "maps:saddr="+sourceName+"&daddr="+destName;`

For Android, the solution needs to be in the [Java part of the plugin](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/android/uk/co/workingedge/phonegap/plugin/LaunchNavigator.java)

If I have time, I will extend the plugin functionality to support an optional source address. In the meantime, you are welcome to do this yourself - if you make a pull request afterwards, this functionality can get integrated into the plugin for the benefit of others.

**Comment by ullasmohan** [comment]
Oh.. thank-you very much for the response. Its perfectly working in my Android device. 
But seems navigation not working in iOS devices. :-(
Am from India and i read an article that ;
"Apple’s own Maps app provides only satellite maps in India.Support for directions, turn-by-turn navigation, 3D view of buildings, local search and traffic information are yet to come to most Apple users outside the US. No wonder Google Maps is still the most popular navigation app in India. It’s also considered to be a lot more accurate than Apple Maps."

Is there any solutions?

**Comment by dpa99c** [comment]
See my reply in [issue #4](https://github.com/dpa99c/phonegap-launch-navigator/issues/3)

**Comment by ullasmohan** [comment]
Thank you very much for your valuable comments.

**Comment by dpa99c** [comment]
v2.1 of the plugin now allows start (source) location to be optionally specified
