### ISSUE TITLE
If google maps or other app are not available

### ISSUE THREAD

**Issue by napcat** [dpa99c/phonegap-launch-navigator#30]
Hello,

Is it possible to ask what app should be used if google maps, bing or apple maps are not available?

I think every iphone/ipad has apple maps and windows device has bing maps, but on Android google maps are not always available (some strange ROM or chinese manufacturer may not include it).

It would be cool if there was a fallback for that situations.
A native window should popup and ask for a default app.

**Comment by dpa99c** [comment]
Each maps app used for navigation (Google Maps/Bing Maps/Apple Maps) has a specific way of passing in parameters such a start/end locations. The plugin has been written to specifically interface with these apps to pass parameters in the required format. Therefore it is not practical to expect the plugin to work arbitrarily with any other navigation app, as each would need to be invoked in a different way and with different parameters. For this reason, the best that can be done on Android is for the plugin to inform the Cordova app using it that Google Maps is not installed. The app creator can use this information to inform the user to install Google Maps, which is free after all.
