### ISSUE TITLE
iOS start location null (current location) causing nothing to happen

### ISSUE THREAD

**Issue by eatpurely** [dpa99c/phonegap-launch-navigator#31]
When using null as a parameter for the start location, it will cause the plugin to do nothing. No handler for success or error is caused. No errors in the xcode logs. Very strange and hard to debug the issue. I am running on iOS 9 device.

Thanks in advance,

Dan

**Comment by dpa99c** [comment]
What version of the plugin are you using? Latest is 2.9.5 - some previous versions had bugs.

Are you able to replicate the problem by running the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example)? There's a [pre-built IPA](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/build/LaunchNavigatorExample.ipa) if you're unable to compile it yourself.

The [first](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/LaunchNavigatorExample/www/index.js#L74) and [second](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/LaunchNavigatorExample/www/index.js#L78) examples in the example project app pass a null parameter for start location. 
This works fine when I test it on iOS 9: [see video here](http://ge.tt/174QzyP2/v/0?c)

**Comment by dpa99c** [comment]
Is this still an issue?
