### ISSUE TITLE
On iOS 9.0.2 preferGoogleMaps: true

### ISSUE THREAD

**Issue by basssolo** [dpa99c/phonegap-launch-navigator#32]
Awesome plugin! I ran into one issue though. Tried to go through docs but could not find anything on this. It seems like on iOS 9.0.2 (could be other versions too) setting preferGoogleMaps: true will open Apple Maps even thought Google Maps is actually available on device. Error: -canOpenURL: failed for URL: "comgooglemaps://" - error: "This app is not allowed to query for scheme comgooglemaps". Did Apple change url politics or did I miss something basic info on this? Maybe I need to register something somewhere for this to work?

**Comment by karlpower6** [comment]
I'm getting this too, also on iOS 9.0.2, launchnavigator 2.9.5

**Comment by karlpower6** [comment]
Add the following to your app's info.plist

<key>LSApplicationQueriesSchemes</key> 
<array> 
<string>comgooglemaps</string> 
</array>

Apple changed some stuff, see here:
http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes

**Comment by karlpower6** [comment]
Solution:

http://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme

Just need to make a small addition to your app's info.plist

**Comment by dpa99c** [comment]
Thanks Karl, when I get time I'll update the plugin documentation to reflect the necessary required additions to the plist for iOS 9 or if possible get the plugin to add the entries directly to the plist

**Comment by basssolo** [comment]
Thanks guys for sorting this out.. Excellent!
