### ISSUE TITLE
ReferenceError: launchnavigator is not defined

### ISSUE THREAD

**Issue by alexverdaguer** [dpa99c/phonegap-launch-navigator#34]
Hi,

I would like to use this plugin with an Ionic App, but I got an error.

I installed with: $ cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator

And in my mainCtrl I call the function : launchnavigator.navigate(destination,source);
but chrome shows me ReferenceError: launchnavigator is not defined in the Console.

Am I missing something ?

Thank you !

**Comment by najie** [comment]
Hi,

I have the same problem and I can't make my code works, even on the iOS emulator.
I'm on ionic.

JS

    $scope.launchNav = function () {
        launchnavigator.navigate(
            "London, UK",
            "Manchester, UK",
            function(){
                  console.log('nice');
            },
            function(error){
            console.log('not nice');
            },
            {
                preferGoogleMaps: true,
                transportMode: "transit",
                enableDebug: true,
                disableAutoGeolocation: true
                }
        );
    }

HTML

    <button class="button icon-left ion-ios-navigate-outline launch-nav-btn"
        ng-click="launchNav()">

$ cordova plugin list

    uk.co.workingedge.phonegap.plugin.LaunchNavigator 2.9.6 "Launch Navigator"

Thanks :)

**Comment by akyriako1978** [comment]
Hi @alexverdaguer @najie I see the thread marked as closed. Have you solved the issue ? Any help would be welcome. Thanks :)

**Comment by akyriakocoursera** [comment]
Hi @alexverdaguer @najie Have you been able to solve this issue ? I see the thread marked as closed. Thanks in advance. :)

**Comment by alexverdaguer** [comment]
Hi,

I did the installation with ionic plugin add
uk.co.workingedge.phonegap.plugin.launchnavigator

 Later I created a button with an ng-click="getDirections(store) and I put
in my controller the following function:

  $scope.getDirections = function (store){
    var destination = [store.lat,store.lng];
    var source = [mipos.lat, mipos.lng];
    launchnavigator.navigate(destination,source);
  }

Hope that helps...

Cheers !


Alex Verdaguer


2015-12-16 16:06 GMT+01:00 Kyriakos Akriotis <notifications@github.com>:
