### ISSUE TITLE
Error on windows cordova platform ""The app can’t use script to load the bingmaps..."

### ISSUE THREAD

**Issue by napcat** [dpa99c/phonegap-launch-navigator#37]
When building to windows 10 (universal app) and I try to lunch the navigation I get this error:

"The app can’t use script to load the bingmaps:?rtp=pos.40.656_-8.6009~pos.39.912856_-8.435529999999972 url because the url launches another app. Only direct user interaction can launch another app."

    var successOpenDirections = function()
    {
           return;
     }

     var errorOpenDirections = function(error)
     {
            return;
     }

     var openDirections = function ()
      {
             launchnavigator.navigate(scope.coords, null, successOpenDirections, errorOpenDirections);
      }

**Comment by dpa99c** [comment]
At first glance, looks like a showstopper to me - Windows 10 seems to outright prevent one app launching another ([see here](https://msdn.microsoft.com/en-us/library/windows/apps/jj860457.aspx)), which is exactly the goal of this plugin.

@opadro did the implementation for Windows 8.x - any thoughts?

**Comment by opadro** [comment]
Give me a few days I will take a look at this.

**Comment by dpa99c** [comment]
@opadro much appreciated

**Comment by opadro** [comment]
@dpa99c created pull request #39 that should fix this bug. Please take a look when you get a chance.

**Comment by dpa99c** [comment]
@opadro thanks for fixing this. I've published your changes to npm as v2.9.9
