### ISSUE TITLE
Windows version does not seem to handle geo coords

### ISSUE THREAD

**Issue by pke** [dpa99c/phonegap-launch-navigator#40]
When using the plugin on Android using geo coords as destination works. However on Windows Phone (8.1) the bing maps app says that it cannot calculate directions.
![wp_ss_20160126_0001](https://cloud.githubusercontent.com/assets/164625/12587003/d32fdbd2-c452-11e5-8bdb-cc5c2eb4f250.jpg)
![wp_ss_20160126_0002](https://cloud.githubusercontent.com/assets/164625/12587000/d085664a-c452-11e5-88be-ef44f424da0d.jpg)

**Comment by dpa99c** [comment]
Looks like you have your longitude and latitude backwards: [6.7530, 51.2314](https://www.google.co.uk/maps/place/6%C2%B045'10.8%22N+51%C2%B013'53.0%22E/@7.1665876,48.7596997,6z/data=!4m2!3m1!1s0x0:0x0) is somewhere in the Arabian Sea off the coast of Somalia (not sure you'd want directions to here - there be pirates!), whereas [51.2314, 6.7530](https://www.google.co.uk/maps/place/51%C2%B013'53.0%22N+6%C2%B045'10.8%22E/@51.2292446,6.7386198,14z/data=!4m2!3m1!1s0x0:0x0) is on a street in Dusseldorf :-)

**Comment by pke** [comment]
hmmm so its the usual order problem. I like the Cartesian coordinates schema with long/lat better so my personal preference might have bitten me here. Thanks!
