### ISSUE TITLE
Open with option

### ISSUE THREAD

**Issue by mustaine** [dpa99c/phonegap-launch-navigator#41]
Hi,

Could be the behaviour similar to when in android is open with google.navigation:?
I mean that is possible to open with navigation apps as citymapper, waze, etc. and you are able to choose with which one open?

Thanks,

**Comment by dpa99c** [comment]
hmm, interesting idea. I think it would need careful consideration and the plugin interface may have to change a bit to accommodate such a feature.

The "open with option" part is user interface-level functionality, so the app using the plugin would need to implement this. The plugin would need to expose a way of detecting and returning which 3rd party navigation apps are installed and available.

Each 3rd party app then needs to expose a protocol which can be used for programmatic instantiation of the app. [Waze](https://www.waze.com/about/dev) and [Citymapper](https://content.citymapper.com/i/864/launching-citymapper-from-apps-and-from-the-web) do this for example.  

Waze only allows a destination lat/lon to be specified, whereas Citymapper also allows start location to be specified, but Google/App Maps allow event more parameters such as transport mode, so there would be a different set of input parameters for each app.

Interestingly, I found a [useful library made by Citymapper](https://github.com/citymapper/CMMapLauncher) that may help a lot with this on iOS. If only they made an android equivalent.

Leave it with me and I'll have a think on it. Good idea, though :+1:

**Comment by weilah** [comment]
It sounds really interesting and a it would be a great feature for the plugin!

**Comment by dpa99c** [comment]
I'm working on this in between, but it involves a complete rewrite of the plugin, so will take some time and be released as v3.
I'm hoping to be able to support the following navigation apps:

Android: Google Maps, Waze, Citymapper, Uber
iOS: Apple Maps, Google Maps, Waze, Citymapper, Uber, Navigon, Transit App, Yandex, TomTom
Windows: Bing Maps

**Comment by yftachman** [comment]
I am also faced with the same problem. Would love for this plugin to support this.

Contact me if i can help with the rewrite :)

**Comment by dpa99c** [comment]
I'm working on it guys. It's quite a major rewrite, but I can't think of any small bits that can I farm out to you. I'm not far off an alpha version, so when I have it, some help testing it to death would be useful. I will publish the git branch both of the plugin and the corresponding example project (also completely rewritten) and post a note here when it's done.

**Comment by dpa99c** [comment]
I've created a first draft of the v3 plugin: it's published on the [v3 branch](https://github.com/dpa99c/phonegap-launch-navigator/tree/v3).
There's also a corresponding [v3 branch of the example project](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/v3) which references it. You should be able to clone this, add a platform, and it should install the v3-dev version of the plugin.

It supports multiple navigation apps on Android and iOS as well as a bunch of other new features. If you have some time to give it a try and give some feedback/bug reports/etc. it would be much appreciated. At this stage it's still in alpha so may contain bugs and is still under development, but I hope to stabilise it for release pretty soon.

**Comment by dpa99c** [comment]
Finally published to npm as 3.0.0
