### ISSUE TITLE
Open in Yandex.Navigator

### ISSUE THREAD

**Issue by vyacheslavtyurikov** [dpa99c/phonegap-launch-navigator#46]
It would be great to be able to open the address in the program Yandex.Navigator

**Comment by dpa99c** [comment]
I'm in the process of rewriting the plugin to allow multiple different navigation apps to be launched. This will be released as v3.

This is covered by #41, so I'll close this as duplicate.

**Comment by dpa99c** [comment]
Note that this is now possible with v3.0.0 of the plugin
