### ISSUE TITLE
Navigator doesn't run [ionic]

### ISSUE THREAD

**Issue by masteruser20** [dpa99c/phonegap-launch-navigator#47]
Hi,

I had worked example in my phone with navigation.
Now Im after some rebuilds, updates(ionic to latest version) and navigation doesn't works on android and on ios.

Here is screen from web serving:
https://i.imgur.com/t0r2hFI.png

When I run application on device , I don't received any errors, just nothing is going on.

I have installed plugin (phonegap plugin add uk.co.workingedge.phonegap.plugin.launchnavigator)

There is a code:
var destination = [50.279306, -5.163158];
            var start = "Trento";
            $cordovaLaunchNavigator.navigate(destination, start).then(function () {
                console.log("Navigator launched");
            }, function (err) {
                console.error(err);
            });

I also add $cordovaLaunchNavigator in controller

**Comment by dpa99c** [comment]
You are treating the plugin as if it's an angular service - it's not, unless you've already created one? - it adheres to the [Cordova plugin API spec](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html). 
Hence if you want to use it in it's pure form, you should be calling:

    var destination = [50.279306, -5.163158];
    var start = "Trento";
    window.launchnavigator.navigate(destination, start, function () {
        console.log("Navigator launched");
    }, function (err) {
        console.error(err);
    });
    
    
If you want to "angularify" it, then create a wrapper service:

    .service('$cordovaLaunchNavigator', ['$q', function($q) {
      "use strict";

      $cordovaLaunchNavigator.navigate = function(destination, start, options) {
          var q = $q.defer();

          window.launchnavigator.navigate(destination, start, function () {
                q.resolve();
            }, function (err) {
                q.reject(err);
          }, options);

          return q.promise;
      };

      return $cordovaLaunchNavigator;
    }]);

Then you can call it as you have been trying to:

    .controller('MyController', function($scope, $cordovaLaunchNavigator) {
        var destination = [50.279306, -5.163158];
        var start = "Trento";
        $cordovaLaunchNavigator.navigate(destination, start).then(function () {
            console.log("Navigator launched");
        }, function (err) {
            console.error(err);
        });
    }

**Comment by dpa99c** [comment]
Reopen if still an issue

**Comment by dpa99c** [comment]
**Update**

I've added an [Ionic example project](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/IonicExample) to the [example project repo](https://github.com/dpa99c/phonegap-launch-navigator-example). It illustrates using this plugin both via its classic Cordova plugin API and as a wrapped Angular service.

There's a [pre-compiled APK](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/build/IonicExample.apk) of it built using v2.9.11 of the plugin.
