### ISSUE TITLE
Suggestion: If start parameter is null...

### ISSUE THREAD

**Issue by cognizen** [dpa99c/phonegap-launch-navigator#49]
Thank you for the great work and sharing it with the community.

I'd like to make a suggestion: if the second (start) parameter is a null or none or some other predefined term, have the map just open to the designated location instead of trying to navigate to the location (I know - the plugin is named navigator and that is it's primary focus).  Seems like this would offer some flexibility.

**Comment by dpa99c** [comment]
I think opening a map view without any navigation intent goes against the aim of this plugin, which is specifically to aid in navigating to a specific destination. Also the plugin is currently undergoing a major rewrite (will be released as v3 - see #41) to support multiple other navigation apps where a "map view" is not possible.
