### ISSUE TITLE
phonegap-launch-navigator not working!!

### ISSUE THREAD

**Issue by developeratmws** [dpa99c/phonegap-launch-navigator#51]
Hi, 
i am new to the phonegap developement, i have npm 2.14.12, cordova 6.0.0, phonegap 5.5.0 installed in my system. i have installed the following plugin in my project:
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-device-motion 1.2.0 "Device Motion"
cordova-plugin-device-orientation 1.0.2 "Device Orientation"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.0 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.2.0 "Splashscreen"
cordova-plugin-whitelist 1.2.1 "Whitelist"
i have installed your plugin in my project and did as you explain in README file, but the plugin does not work. i have also tried "typeof launchnavigator" to check whether the object exists or not but it says undefined.

UPDATE: 
here is my code: 
```
document.addEventListener('deviceready', function () {
            $("#button").click(function () {

                launchnavigator.navigate(
                        [50.279306, -5.163158],
                        [50.342847, -4.749904],
                        function () {
                            alert("Plugin success");
                        },
                        function (error) {
                            alert("Plugin error: " + error);
                        });


            });
        }, false);
```

Please Help!!!
Thanks.

**Comment by dpa99c** [comment]
If the `launchnavigator` object is not defined, this would indicate the plugin is not properly installed in the project.

It would help to know:

- What platform (Android/iOS?) you are testing on?
- What device/OS version?
- What Cordova platform version? (
    - locally: `cordova platform ls`
- Whether you are building locally or remotely (e.g. Phonegap Build)?
- How you are installing the plugin? 
    - e.g. `cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`

Assuming you're building locally:
- Check that `plugins/` contains `uk.co.workingedge.phonegap.plugin.launchnavigator` folder
- Run the app and connect a remote debugger (Chrome Dev Tools for Android / Safari Web Inspector for iOS). Inspect the Resources being loaded and check that `launchnavigator.js` is present. If not, the plugin is not correctly installed.
- Try building and running the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example)

**Comment by developeratmws** [comment]
@dpa99c thanks for your quick reply, let me check all the things as you mentioned, will update you.

**Comment by developeratmws** [comment]
Hi, 
- I am using phonegap as a server and starting that server as "phonegap serve"
- I am testing on android using phonegap developer app also using browser to check the DOM and console logs by access the URL 192.x.x.x:3000.
- Cordova platform version: android 4.1.1, browser 4.0.0
- I am building the app remotly using phonegap remote build android.
- i have installed the plugin using: phonegap plugin add uk.co.workingedge.phonegap.plugin.launchnavigator

after installation i did phonegap plugin ls and it shows me [http://oi68.tinypic.com/2i1gqw6.jpg](url).
when i launch it in web browser it show the error [http://oi64.tinypic.com/30ihwmd.jpg](url)

Please help.

**Comment by dpa99c** [comment]
OK, to clarify this plugin is intended to launch a **native** navigation app. That means it must be run in a **native** mobile environment, i.e. on an Android/iOS/Windows physical device or device emulator. 

It will not work in the browser, since there's no **native** navigation app to launch, i.e. Google Maps, Apple Maps, Bing Maps.

If you want to test it, you need to run it on a real device, i.e. `phonegap run android`
