### ISSUE TITLE
[Question] is there any update detail in 3.0.0 version ?

### ISSUE THREAD

**Issue by bau720123** [dpa99c/phonegap-launch-navigator#53]
hi @dpa99c 
just want to ask
is there any update detail information in 3.0.0 version ?

because in the 3.0.0 version，I saw you use the "cordova-plugin-actionsheet" and integrate to your own self，any reason or new function ?

**Comment by dpa99c** [comment]
cordova-plugin-actionsheet is used to display a native picker (both on Android and iOS) to choose which available navigation app should be used. This is used if [app](https://github.com/dpa99c/phonegap-launch-navigator#app) is specified as `launchnavigator.APP.USER_SELECT`, which is now the default is on v3 if an app is not explicitly specified. I'll update the [version notes](https://github.com/dpa99c/phonegap-launch-navigator#version-notes) section to make this explicitly clear.

**Comment by dpa99c** [comment]
Resolved by dace719

**Comment by bau720123** [comment]
awesome @dpa99c 
I will study the latest document
thanks
