### ISSUE TITLE
Help using the plugin.

### ISSUE THREAD

**Issue by Greg4572** [dpa99c/phonegap-launch-navigator#56]
Hi
I've only recently starting with mobile development and i am working on a HTML5/JavaScript app that will navigate to a destination using the users's phones native navigation apps when a button is clicked. We are already using phonegap/cordova to get geolocation and a few other things but i have never used phonegap or cordova before. I really want to use this plugin as it is very nice and will do exactly what i need but i really don't know how to get it to work. I have tried placing the plugin in the config.xml file and then used the code from the Usage Examples area but that just doesn't work. I have also tried to use node.js to try install the plugin that way but i am finding it very confusing. So any advice or documentation that will help with learning how to get it working will be very helpful.
(sorry if i am asking this in the wrong place)

**Comment by dpa99c** [comment]
You should start by following the [Cordvova getting started guide](https://cordova.apache.org/docs/en/latest/guide/cli/index.html) to learn how to use Cordova.

This plugin follows the standard Cordova spec, so is installed in the standard way: the [installation section](https://github.com/dpa99c/phonegap-launch-navigator#installing) of the documentation instructs how to install the plugin using various standard Cordova/Phonegap methods.

The [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) illustrates how to use the plugin, so you should use this as a reference.

**Comment by Greg4572** [comment]
Great, thanks for the quick reply. Ill give that a shot, hopefully it will help me out.
