### ISSUE TITLE
launch navigator is not define

### ISSUE THREAD

**Issue by getlose** [dpa99c/phonegap-launch-navigator#57]
Hi, I tried to implement this plugin in my ionic app but the error comes up and it says "launchnavigator is not define" 
then I try your ionic example on several devices, the same problem also occurs.
what should i do to overcome this problem? thanks

**Comment by dpa99c** [comment]
If the `launchnavigator` object is not defined, this would indicate the plugin is not properly installed in the project.

It would help to know:

- What platform (Android/iOS?) you are testing on?
- What devices/OS versions?
- What Cordova platform version? 
    - locally: `cordova platform ls`
- Whether you are building locally or remotely (e.g. Phonegap Build)?
- How you are installing the plugin? 
    - e.g. `ionic plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`

Assuming you're building locally:
- Check that `plugins/` contains `uk.co.workingedge.phonegap.plugin.launchnavigator` folder
- Run the app and connect a remote debugger (Chrome Dev Tools for Android / Safari Web Inspector for iOS). Inspect the Resources being loaded and check that `launchnavigator.js` is present. If not, the plugin is not correctly installed.

**Comment by getlose** [comment]
I am testing on android 5.0
and `cordova platform ls` contain

```
Installed platforms:
  android 4.1.1
  ios 3.9.2
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.3.1
  wp8 ~3.8.2 (deprecated)
```

I build it locally then install the plugin using
`cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`

I check chrome console that `launchnavigator.js` is not present.
and I already try re-Installing the plugin but still got the same problem.
is the method of installing this plugin is different with ionic? 

I already mentioned that I have run the ionic example for this plugin and got the same problem.

**Comment by dpa99c** [comment]
> I build it locally then install the plugin using `cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`

I assume you mean "install the plugin then build it locally"? Because if you "build it locally then install the plugin" then the plugin will not be present at build time and therefore won't be present in the app.

> is the method of installing this plugin is different with ionic?

I believe the ionic way of doing it is `ionic plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`

Before building, I suggest making sure that:
- the plugin folder is present: `plugins/uk.co.workingedge.phonegap.plugin.launchnavigator`
- the plugin is present in the platform project: `platforms/android/platform_www/plugins/uk.co.workingedge.phonegap.plugin.launchnavigator/`

**Comment by getlose** [comment]
I try to reinstall with `ionic plugin add uk.co.workingedge.phonegap.plugin.launchnavigator` and still got the issue as in the picture.
![screenshot_2016-04-01-13-14-06](https://cloud.githubusercontent.com/assets/9418416/14199253/f4b19c6c-f80c-11e5-8c70-2243e8f3c042.jpg)

the I realize that the problem occur on 

```
$cordovaLaunchNavigator.navigate(dest, {
        start: start,
        enableDebug: true
      }).then(function () {
        alert("Navigator launched");
      }, function (err) {
        alert(err);
      });
    };
```

It come to `alert(err);` 
I check the plugin folder and all are present.

**Comment by dpa99c** [comment]
I'm still not able to reproduce your issue. See [this screen capture video](http://ge.tt/8RFdSbZ2) which shows how it's running on my system (Windows 10). It also builds and runs Android and iOS fine on my Mac  (OSX 10.11).

**Comment by dpa99c** [comment]
Is this still an issue or can it be closed?

**Comment by getlose** [comment]
Sorry for not replying. I have been hospitalized since last week. I not touch my project yet. Can this topic open until I am ready for my project? Hope I can recover soon.

**Comment by dpa99c** [comment]
Sure, I will leave it open then. Just wanted to check. Hope you get well soon.

**Comment by getlose** [comment]
Thanks for the condition. I watch your video and i think I got the problem. The problem is the way I run the ionic project. In your video, you are running it on the emulator while I am on the phonegap android application. So i try to run in on my real android and it works like charm. Thanks!
