### ISSUE TITLE
successCallback and errorCallback options wrong documented 

### ISSUE THREAD

**Issue by marck1991** [dpa99c/phonegap-launch-navigator#58]
In the README.md -> API methods -> navigate() -> Parameters -> Options
You are writing "successFn:" and "errorFn:", but it has to be "successCallback:" and "errorCallback:" ...

For example the way it performs well:
launchnavigator.navigate(dest, {
        successCallback: successMethode,
        errorCallback: errorMethode
    });

An example which I wrote suggested by your documentation and which DOESN'T work:
launchnavigator.navigate(dest, {
        successFn: successMethode,
        errorFn: errorMethode
    });

Thanks in advance for correcting and thanks a lot for your plugin, I'm so happy with it =)

**Comment by dpa99c** [comment]
Thanks, well spotted, I missed this when I changed the parameter names from v2. Will update the docs.
