### ISSUE TITLE
 launchnavigator.isAppAvailable(launchnavigator.APP.GOOGLE_MAPS returns false

### ISSUE THREAD

**Issue by zulalay** [dpa99c/phonegap-launch-navigator#59]
i tried  launchnavigator.isAppAvailable(launchnavigator.APP.GOOGLE_MAPS, function (isAvailable) {...})
from the example for my android and it returns false. However it is listed as available in launchnavigator.availableApps and also works when i use launchnavigator.navigate and specify optional parameter
app: launchnavigator.APP.GOOGLE_MAPS

**Comment by MattDavies** [comment]
Seeing the same behaviour right now on Android.

Came up with this workaround for the moment:

launchnavigator.availableApps(function(availableApps) {
    var isAvailable = availableApps[launchnavigator.APP.GOOGLE_MAPS];
    if (isAvailable) {

**Comment by dpa99c** [comment]
Yep, I'm able to reproduce this. Seems I forgot to add a specific test for this API method in the example project (oops). I've now added one and will fix this bug in the next release. 

FYI it currently all explicitly supported apps on Android: Google Maps, Waze, Citymapper, Uber
