### ISSUE TITLE
Enable app-specific options to be specified

### ISSUE THREAD

**Issue by armensg** [dpa99c/phonegap-launch-navigator#60]
More of a question than an issue: does this plugin allow passing a custom URI or options to the URI? for example to pass a client_id and product_id to the Uber app?

**Comment by dpa99c** [comment]
Currently the plugin doesn't enable you to do this, but it would be a nice enhancement. I'm thinking you would pass these app-specific parameters as a key/value structure and let the plugin map that back to URL parameters, i.e.

    {
      client_id: "some_client"
    }

would map to `...&client_id=some_client`

Added it to my todo list.

**Comment by coderroggie** [comment]
I believe this would also help me in my quest to add the "avoidTolls" option to google maps when getting directions in google maps.  That would be big for me.  See (http://stackoverflow.com/questions/1056984/open-google-maps-to-bus-directions/1057648#1057648) for something similar.

**Comment by coderroggie** [comment]
Sweet, thanks!
