### ISSUE TITLE
Lat/Lng are being slightly changed on iOS

### ISSUE THREAD

**Issue by rafaelcoutinho** [dpa99c/phonegap-launch-navigator#61]
Hi,

I'm using the API passing Lat/Lng as destinations, however for some reason they are getting "updated" on iOS. The original lat/lng 
-23.254565,-47.232821 
are becoming 
-23.265697,-47.299124
I'm sure about the original lat/lng values, and when we select Gmaps I can see quickly the values passed to it which does not match.

What is the cause of this?

**Comment by rafaelcoutinho** [comment]
now i have tried with:
-23,-47 
and it becomes 
22.996404,-47.002055

**Comment by rafaelcoutinho** [comment]
Humm found out why, it ALWAYS force a reverse geocode on my initial coordinates, and since the coordinates are not in town, it "fixes" it. However Waze can find the location with the original coordinates. I'm forking and make a hotfix, but eventually I'll try to send a PR.

**Comment by dpa99c** [comment]
Fixed by commit 6deeace7e326b1edda49f5c270c0e6e78b0dc6b4

**Comment by rafaelcoutinho** [comment]
Well I just didn't understand why we need the reverse geocoding.

I have done a different solution in here:
https://github.com/rafaelcoutinho/phonegap-launch-navigator

**Comment by coderroggie** [comment]
I agree with @rafaelcoutinho.  I've found some of the mapping solutions to be completely off-base when used, so I would prefer to be able to send them straight to and always straight through to google maps without the geo-coding.  Any chance we could get an option like he has implemented in this plugin?
