### ISSUE TITLE
Doesn't work on published api (ionic) 

### ISSUE THREAD

**Issue by thiagoantunes** [dpa99c/phonegap-launch-navigator#62]
The launchnavigator.navigate(destination) works fine when debugging, but when I publish the apk it doesn't work on android devices. Should I set something on config.xml or androidmanifest?

**Comment by dpa99c** [comment]
There's no additional requirement for production builds vs debug builds. From a Cordova plugin perspective, the environment is identical. I am using this plugin in multiple Android apps that are live in the Google Play store and there are no issues. I suggest further investigation of your codebase.

Also, you can try building and running the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) apps for a reference - there's an Ionic example in there too.

**Comment by thiagoantunes** [comment]
I'm using the exact same code of the example but it's throwing the exception "launchnavigator is not defined". Only when publishing. During development works perfectly.

**Comment by dpa99c** [comment]
I've built and publish the example app to the Google Play store (which I was going to do anyway). It works fine for me. Please try it: https://play.google.com/store/apps/details?id=workingedge.example.launchnavigator.ionic

**Comment by dpa99c** [comment]
Reopen if still an issue.
