### ISSUE TITLE
launch with a address

### ISSUE THREAD

**Issue by colonna-mike** [dpa99c/phonegap-launch-navigator#64]
is there a way to launch with a address?

for example: 
launchnavigator.navigate("100 country crossing circle, magnolia TX 77345");
If so, is the above string correct?

**Comment by dpa99c** [comment]
Yes, as [shown in the documentation](https://github.com/dpa99c/phonegap-launch-navigator#navigate-to-a-destination-address-from-current-location) you can use either an address or coordinate for destination/start locations, so your above example will work. The native navigation app that you launch will geocode the address you pass to it, so as long as the address is valid, the navigation app will find it.

**Comment by colonna-mike** [comment]
thank you, worked great
