### ISSUE TITLE
Request to add Sygic support

### ISSUE THREAD

**Issue by stevensomer** [dpa99c/phonegap-launch-navigator#65]
Hi Dave,

Great work! Could you please also add support for Sygic as well? It would help me a lot.

Example URL for both Android and iOS is:
com.sygic.aura://coordinate|17.12812|48.15594|drive

Documentation:
https://developers.sygic.com/documentation.php?action=customurl_ios

**Comment by dpa99c** [comment]
Added to my TODO list

**Comment by dpa99c** [comment]
Support added in v3.1.0 by commit e337404bdae0c9c2dbb34d940107d92b44b45933
