### ISSUE TITLE
Marker on map

### ISSUE THREAD

**Issue by AlexandrMozolevsky** [dpa99c/phonegap-launch-navigator#66]
Hello, 
How can I display only marker on applications? Not the route, Is it possible?
Thanks

**Comment by dpa99c** [comment]
The purpose of this plugin is to launch navigation apps for the purposes of navigating a route to a destination. Therefore, opening apps in a "non-route-navigation" mode is beyond the scope of this plugin.

While some of the navigation apps supported by this plugin are also mapping apps (e.g. Google Maps, Apple Maps) and therefore can be launched in a non-route navigation mode (i.e. "marker on map view"), others are purely navigation apps (e.g. Waze, Yandex) and so have no equivalent non-route navigation mode.

**Comment by AlexandrMozolevsky** [comment]
Thank you!
