### ISSUE TITLE
Enable edit app selection dialog header

### ISSUE THREAD

**Issue by aluferraz** [dpa99c/phonegap-launch-navigator#67]
Hi,

I think it would be nice to enable to edit the app selection dialog header. Currently we have the predefined text "Select app for navigation", but if we had a option to edit it, it would be possible to translate the header text to another languages.

Thanks !

**Comment by aluferraz** [comment]
It would be nice if we could edit the "Cancel" button text too...

**Comment by dpa99c** [comment]
Yes, good idea for localisation. Added to my todo list.

**Comment by danielcrk-cn** [comment]
This would be great, right now, I had to edit the strings in common.js.
Such an awesome plugin, thanks so much for this! :)

**Comment by dpa99c** [comment]
published to npm as v3.1.0
