### ISSUE TITLE
Is there a way to let the user choose the navigation app on first invoke

### ISSUE THREAD

**Issue by pke** [dpa99c/phonegap-launch-navigator#68]
Some users have more than one navigation app installed.
Is there a way to make launch-navigator display a selector via native functionality. 
Or do I have to query the available apps myself and present such a list to the user?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/phonegap-launch-navigator#app-detection-selection-and-launching), by default the plugin will detect if more than one supported app is installed, and if a specific app is not specified, it will present a native dialog to allow the user to select which app to use.

You can try building/running one of the example apps in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) which illustrates this.
