### ISSUE TITLE
App crashes on windows phone

### ISSUE THREAD

**Issue by arnevdv** [dpa99c/phonegap-launch-navigator#69]
When I try to launch the navigator on my windows phone, my app crashes instantly.
This is my code:
```
openNavigator(location) {
        launchnavigator.navigate(location);
    }
```

Any suggestions? It works on iOS and Android...

**Comment by dpa99c** [comment]
What version of Windows Phone are you seeing the issue on and what (is any is the error message)?

**Comment by arnevdv** [comment]
It's a Lumia 640 with Windows 10 on it. No error message...

**Comment by dpa99c** [comment]
Just tried the [SimpleExample](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/SimpleExample) from the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) on a Lumia 535 running Windows 10 Mobile and it works fine.

**Comment by dpa99c** [comment]
Reopen if still an issue
