### ISSUE TITLE
Launchnavigator is not defined

### ISSUE THREAD

**Issue by fadao23** [dpa99c/phonegap-launch-navigator#72]
Hi i tried the exmaple disponible in this link https://github.com/dpa99c/phonegap-launch-navigator-example, but i does not work.. I have this porblem : "Lauchingnavigator is not defined".. 

what should i do to overcome this problem? thanks

**Comment by dpa99c** [comment]
I would assume the error message is "**launchnavigator** is not defined" as opposed to "**Lauchingnavigator** is not defined" ??

This error would most likely indicate that the plugin is not properly installed in the Cordova project. Please check that `{project}/plugins/uk.co.workingedge.phonegap.plugin.launchnavigator` exists. 

Please also provide the following information:

- The example repo contains 3 projects: SimpleExample, AdvancedExample, and IonicExample - which are you trying to build?
- What platform/version/device you are testing on (e.g. Android/6.0/Nexus 6 or iOS/9.3.2/iPhone 6s)??
- Are you building locally or in a cloud environment (e.g. Phonegap Build)?

**Comment by fadao23** [comment]
Hi, I see similar problem in forum.. And i have downloaded this video http://ge.tt/8RFdSbZ2.. 

I have followed yours intructions but i Hve this problem now : 
![l](https://cloud.githubusercontent.com/assets/19324896/15471175/fed737fe-20f4-11e6-84e3-43c5c7e2e217.png)

For reply your answer : 

- I have take the "IonicExample"
- I have trie wich my Galaxy S5 (samsung) and now i trie withc emulator "Nexux 5" 
- I build locally with cordova (android studio) and too with ionic CLI "ionic run android"

Thanks Fernando.

**Comment by dpa99c** [comment]
OK, I can reproduce it and found the cause. There's a [line left over in the Android JS implementation](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/android/launchnavigator.js#L1) when I copied it from the platforms/android/ folder that is being duplicated by Cordova and this is causing the issue. I will fix it and push out as a patch release now.

**Comment by dpa99c** [comment]
try removing plugin (`ionic plugin rm uk.co.workingedge.phonegap.plugin.launchnavigator`) and re-adding (`ionic plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`) as v3.1.1 published to npm should fix this

**Comment by DanRamGim** [comment]
I had this error, the only way for me to fix it is to delete the plugin from my folders, but keep it named inside your config, that way when you build your solution, it will automatically download again the plugin and it will work.

**Comment by YajJackson** [comment]
@DanRamGim I would love to know if there is a better way to ensure that the proper plugin is installed. Why should we need to delete a directory that contains existing plugins just to force a new install? I have seen that this works, but think we should investigate a better method.

**Comment by fadao23** [comment]
@YajJackson You can maybe try :
`npm update`

But in all threads that I read, the method used by everybody is :

`rm -rf node_modules && npm install`
