### ISSUE TITLE
Launch map without directions, just a location

### ISSUE THREAD

**Issue by lehresman** [dpa99c/phonegap-launch-navigator#78]
This plugin is exactly what I need, except I don't want it to launch with directions.  I want it to just launch with a point selected on the map.  Is this possible?  I didn't see anything in the docs about it.  If not, any chance you could add it?

Perhaps:  `launchnavigator.point(addr)`

**Comment by dpa99c** [comment]
The purpose of this plugin is specifically (as the name implies) to launch navigation apps for routing purposes. As such, some of the apps which are currently supported are not able to be launched in (or do not have a ) "map mode". Therefore I think this lies outside the scope of what this plugin is intended for (i.e. route navigation).

This would be best accomplished by a dedicated plugin that specifically launches mapping apps with a specified location, as not all mapping apps also support route navigation - e.g. [co.medicast.plugins.maplauncher](https://github.com/medicast/cordova-plugin-maplauncher)
