### ISSUE TITLE
Specified app was not opening 

### ISSUE THREAD

**Issue by bedapudi** [dpa99c/phonegap-launch-navigator#80]
I need to open the navigator in google maps.  and i am doing as follows,

var app = launchnavigator.APP.GOOGLE_MAPS;
$cordovaLaunchNavigator.navigate(destination, start,{app:app})

Still it is listing the apps to choose " select app for navigation (Uber, Google Maps) " 
Is this an issue?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/phonegap-launch-navigator#navigate), the call signature for `navigate()` is either:

    launchnavigator.navigate(destination, options);

or

    launchnavigator.navigate(destination, successCallback, errorCallback, options);

However, by using

    $cordovaLaunchNavigator.navigate(destination, start,{app:app})

you are using an invalid signature:

    launchnavigator.navigate(destination, start, options);

This means neither the start or options object you pass in will be used - start will default to the current device location,

Change your code to invoke the function using a valid signature, for example:

    $cordovaLaunchNavigator.navigate(destination, {
      app:app,
      start: start
     });

You can find a working example of how to specify the app in the [Advanced Example](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/AdvancedExample) of the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example)

**Comment by bedapudi** [comment]
i am trying  this,
$cordovaLaunchNavigator.navigate(destination,  {app: app, start: start});

there is a warning in the console,
launchnavigator.navigate() called using deprecated v2 API signature. Please update to use v3 API signature as deprecated API support will be removed in a future version

Popup is being shown with uber and google and when i select one on them , nothing happens
