### ISSUE TITLE
Need callback from googlemaps App using phonegap-launch-navigator

### ISSUE THREAD

**Issue by inplamba** [dpa99c/phonegap-launch-navigator#82]
Hey @dpa99c
I am Using Launch Navigator for opening Google Maps App ,Can this plugin provide success callback (Means when we reached the destination in google maps App from starting point) it gives us success that user reached the destination

Thanks in Advance

**Comment by dpa99c** [comment]
@inplamba no, triggering a success callback when Google Maps reaches its destination is entirely not possible. Google Maps does not provide such a cross-app communication mechanism and neither do any other of the supported navigation apps.
