### ISSUE TITLE
Toggle Geocoding

### ISSUE THREAD

**Issue by Reubend** [dpa99c/phonegap-launch-navigator#84]
First of all, let me just say that this is a fantastic plugin! It works really well and there are a ton of added features since when I checked in last.

Is there any way to disable the custom geocoding? I want to launch Google Maps with exactly the string that I entered, instead of giving it a lat/lon coordinate. But this plugin seems to be geocoding it into an incorrect lat/lon and then starting Gmaps with that instead of the original string.

**Comment by dpa99c** [comment]
This is a bug in the iOS implementation. It shouldn't be unnecessarily geocoding like this,
