### ISSUE TITLE
Issue in aborting http calls after 20 seconds

### ISSUE THREAD

**Issue by inplamba** [dpa99c/phonegap-launch-navigator#85]
Hey @dpa99c,
I am facing an issue in Ionic ,Please help me Out . I am trying to abort my http post and get request after 20 seconds and want to execute the http call error block which says "server issue found"  .Is there is any way to abort http call and execute its error block in ionic or cordova .Thanks in Advance

**Comment by dpa99c** [comment]
How is your aborting of an HTTP request related to a possible bug with this plugin?
