### ISSUE TITLE
NATIVE APP SELECTION

### ISSUE THREAD

**Issue by clembou590** [dpa99c/phonegap-launch-navigator#87]
This is a new feature request:
when calling:
launchnavigator.navigate("London, UK");

it would be great if we could set a list of app the user can select.
Exemple:
if on the phone there is: GMAPS,WAZE,UBER.
what I would like to do is this:

_var selectableApps = [launchnavigator.APP.GOOGLE_MAPS,launchnavigator.APP.WAZE];
launchnavigator.navigate("London, UK",selectableApps );_

the user would then only have the choice between GMAPS and WAZE (and not UBER).

**Comment by dpa99c** [comment]
Added to TODO list

**Comment by clembou590** [comment]
thanks.
Any idea on when you can do it?
thanks again for the very very nice work already done
