### ISSUE TITLE
Phonegap build - IOS not working

### ISSUE THREAD

**Issue by farhanfarrukh** [dpa99c/phonegap-launch-navigator#9]
Hi I'm using phonegap build to use this plugin it is working perfectly fine on android devices however its not working properly on IOS.

```function navigate() {
	launchnavigator.navigate([25.180047, 55.224282],null,onSuccess,onError);
}```	

This is the code that I'm using which on Android it ask me for the my current location and starts the navigation. However, on IOS the same code opens APPLE MAP but don't ask me for my current location neither carries [25.180047, 55.224282] destination over.

Any idea on why this is happening?

**Comment by dpa99c** [comment]
What version of iOS are you testing with and are you having this issue with the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) also? The example has been tested on iPad 2 running iOS 8.1.1 and iPhone 4S running iOS 7.0 and all 4 examples in the project work fine in these versions.

**Comment by farhanfarrukh** [comment]
Sorry I haven't tested the Example Project but I'm using iPAD Air with the lastest IOS available. One thing that I forgot to mention is I'm using Phonegap build if that makes any difference? I will test that example project and will get back to you.

Thanks for a quick reply

**Comment by 05bca054** [comment]
Hello,

Let me thank you first for awesome piece of work.

But i also facing the same issue on iphone latest OS IOS 8.2

When passing null it ask for current location that's fine, but once i set current location and then press route "A route cannot be determined from this start location" i got this.

launchnavigator.navigate([23.180047, 73.224282],null,onSuccess,onError);

Thanks for your time and consideration in advance.

-Niks

**Comment by dpa99c** [comment]
@Niks: I noticed your destination, 23.180047, 73.224282, is Gujarat in India. Apple Maps currently doesn't support "turn-by-turn" navigation in India: https://www.apple.com/in/ios/feature-availability/#maps-turn-by-turn-navigation

See [this previously raised issue](https://github.com/dpa99c/phonegap-launch-navigator/issues/4)

@farhanfarrukh: Same for you - Apple Maps doesn't support "turn-by-turn" navigation in UAE

**Comment by dpa99c** [comment]
Closing this issue as it's down to Apple Maps not supporting navigation in certain countries, rather than a bug with the plugin
