### ISSUE TITLE
phonegap build not working

### ISSUE THREAD

**Issue by tejasghutukade** [dpa99c/phonegap-launch-navigator#90]
I tried the phonegap build for android and ios both didnt work.
the i build the android project and installed it via android studio and it worked.
whats need to be done in order to make it work using phonegap build?

**Comment by dpa99c** [comment]
Building the example project in phonegap build works fine for Android, iOS and Windows (see screenshot below). You can try building it yourself in PGB:
- Repo URL: https://github.com/dpa99c/phonegap-launch-navigator-example
- Branch / Tag: phonegap_build

![fireshot capture 85 - adobe phonegap build - https___build phonegap com_apps_2253067_builds](https://cloud.githubusercontent.com/assets/2345062/18351339/a2973322-75d1-11e6-948c-bfe563311b1d.png)
