### ISSUE TITLE
Please how to set appSelectionDialogHeader

### ISSUE THREAD

**Issue by renanverri** [dpa99c/phonegap-launch-navigator#91]
i need translate this header ...  ''SELECT APP FOR NAVIGATION'' 

anyone know how to set this ?
because i try all time and failed...

**Comment by dpa99c** [comment]
This was added in [v3.1.0](https://github.com/dpa99c/phonegap-launch-navigator/tree/3.1.0) after request in #67. 

Usage:

    launchnavigator.navigate([50.279306, -5.163158], {
        start: "50.342847, -4.749904",
        appSelectionDialogHeader: "Custom Header Text",
        appSelectionCancelButton: "Custom Cancel Text"
    };

I will add an explicit example in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example)

**Comment by dpa99c** [comment]
Try the [AdvancedExample](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/AdvancedExample) which gives a [code illustration](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L101) of how to do this.

**Comment by renanverri** [comment]
launchnavigator.navigate([source, destination], {
    appSelectionDialogHeader: "Custom Header Text",

});

this is right ?  because i think you lost to put  the ")"
