### ISSUE TITLE
iOS 10, Xcode 8, 2 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by Emadello** [dpa99c/phonegap-launch-navigator#92]
Xcode build failed and I'm getting the following error:

duplicate symbol _CMEmptyAddress in:
.../CMMapLauncher.o
.../LaunchNavigator.o

duplicate symbol _CMEmptyCoord in:
.../CMMapLauncher.o
.../LaunchNavigator.o

2 duplicate symbols for architecture arm64
linker command failed with exit code 1 (use -v to see invocation)

**Comment by Emadello** [comment]
changing 'No Common Blocks' from Yes to No ( under Targets->Build Settings->Apple LLVM - Code Generation ) fixed the problem.

**Comment by dpa99c** [comment]
Since this setting (GCC_NO_COMMON_BLOCKS) defaults to No in a new Cordova XCode project, I'm closing this on the basis it's not an issue with the plugin itself.

**Comment by wdss93** [comment]
It did not work for me.

**Comment by pideni** [comment]
@Emadello you saved my weeks!!!!! Thank you been looking for solution to this issue for so long. Damn it was so easy to fix.

**Comment by imdadturi** [comment]
It did not work for me

**Comment by deblinaalways** [comment]
It didn't work for me either!

**Comment by gunduzcihat** [comment]
it didn't work!

**Comment by samuelmorais** [comment]
It worked for me! Thanks @Emadello !

**Comment by franknoel** [comment]
For those who this wasn't working, what did you do instead?

**Comment by kristofvdj88** [comment]
This isn't working for me either. I did find the "Apple Clang - Code generation" setting section with the "No Common Blocks" setting in it but this was already set to Yes... 

What's causing this? Stuck here...

**Comment by prajjwal81** [comment]
yet not working
