### ISSUE TITLE
Support for UrbanCycles

### ISSUE THREAD

**Issue by vosecek** [dpa99c/phonegap-launch-navigator#97]
Navigation specialized for urban cycling (http://urbancyclers.com/)

App is in this time for Android only, iOS version will follow.

Link scheme: http://urbancyclers.cz/plan/#olat=50.100542&olon=14.395094&dlat=50.067167&dlon=14.415522

olat, olon - start (not required, will be used user position if missing start coords)
dlat, dlon - destination

Important information - app version in Google Play does not support this link yet, but it will support in a few days. This link has been tested with development version.

**Comment by dpa99c** [comment]
Finally got around to implementing this, but the URL scheme above does not seem to work. Tested on Android using the example URL above and result is "Route not found":

<img src="https://user-images.githubusercontent.com/2345062/30746586-1f300b52-9fa2-11e7-8231-bf6c4d691111.png" width="200">

Logcat doesn't show much:

    09-22 14:18:34.351 23779-23978/workingedge.example.launchnavigator.advanced D/LaunchNavigator: Plugin action=navigate
    09-22 14:18:34.352 23779-23978/workingedge.example.launchnavigator.advanced D/LaunchNavigator: Called navigate() with args: app=urban_cyclers; dType=pos; dest=["51.498739","-0.133827"]; destNickname=Some place; sType=pos; start=["53.493002","-2.240080"]; startNickname=My place; transportMode=d; launchMode=maps; extras=null; enableGeocoding=true
    09-22 14:18:34.353 23779-23978/workingedge.example.launchnavigator.advanced D/LaunchNavigator: Using UrbanCycles to navigate from [53.493002,-2.240080] to [51.498739,-0.133827]
    09-22 14:18:34.353 23779-23978/workingedge.example.launchnavigator.advanced D/LaunchNavigator: URI: http://urbancyclers.cz/plan/#olat=50.100542&olon=14.395094&dlat=50.067167&dlon=14.415522
    09-22 14:18:34.363 800-811/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://urbancyclers.cz/... cmp=com.android.chrome/com.google.android.apps.chrome.Main} from uid 10223
    09-22 14:18:34.370 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: file:///android_asset/www/index.js: Line 136 : User selected app: urban_cyclers
    09-22 14:18:34.371 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaWebViewImpl: >>> loadUrl(javascript:console.log("LaunchNavigator[native]: Plugin action=navigate"))
    09-22 14:18:34.373 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaWebViewImpl: >>> loadUrl(javascript:console.log("LaunchNavigator[native]: Called navigate() with args: app=urban_cyclers; dType=pos; dest=[\"51.498739\",\"-0.133827\"]; destNickname=Some place; sType=pos; start=[\"53.493002\",\"-2.240080\"]; startNickname=My place; transportMode=d; launchMode=maps; extras=null; enableGeocoding=true"))
    09-22 14:18:34.373 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaWebViewImpl: >>> loadUrl(javascript:console.log("LaunchNavigator[native]: Using UrbanCycles to navigate from [53.493002,-2.240080] to [51.498739,-0.133827]"))
    09-22 14:18:34.374 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaWebViewImpl: >>> loadUrl(javascript:console.log("LaunchNavigator[native]: URI: http://urbancyclers.cz/plan/#olat=50.100542&olon=14.395094&dlat=50.067167&dlon=14.415522"))
    09-22 14:18:34.378 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaActivity: Paused the activity.
    09-22 14:18:34.407 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: file:///android_asset/www/index.js: Line 120 : Launched navigator app
    09-22 14:18:34.408 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: : Line 1 : LaunchNavigator[native]: Plugin action=navigate
    09-22 14:18:34.409 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: : Line 1 : LaunchNavigator[native]: Called navigate() with args: app=urban_cyclers; dType=pos; dest=["51.498739","-0.133827"]; destNickname=Some place; sType=pos; start=["53.493002","-2.240080"]; startNickname=My place; transportMode=d; launchMode=maps; extras=null; enableGeocoding=true
    09-22 14:18:34.410 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: : Line 1 : LaunchNavigator[native]: Using UrbanCycles to navigate from [53.493002,-2.240080] to [51.498739,-0.133827]
    09-22 14:18:34.412 23779-23779/workingedge.example.launchnavigator.advanced D/SystemWebChromeClient: : Line 1 : LaunchNavigator[native]: URI: http://urbancyclers.cz/plan/#olat=50.100542&olon=14.395094&dlat=50.067167&dlon=14.415522
    09-22 14:18:34.427 800-5387/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://urbancyclers.cz/... flg=0x14002000 cmp=com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity (has extras)} from uid 10039
    09-22 14:18:35.062 23779-23779/workingedge.example.launchnavigator.advanced D/CordovaActivity: Stopped the activity.
    09-22 14:18:35.180 800-8846/? I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=http://urbancyclers.com/... flg=0x10000000 cmp=com.umotional.bikeapp/.ui.ride.RideActivity (has extras)} from uid 10039
    09-22 14:18:35.515 21215-21215/? D/EventBus: No subscribers registered for event class com.umotional.bikeapp.messages.RedeliverMessage
    09-22 14:18:35.516 21215-21215/? D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
    09-22 14:18:35.528 21215-21215/? D/EventBus: No subscribers registered for event class com.umotional.bikeapp.messages.RedeliverMessage
    09-22 14:18:35.528 21215-21215/? D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
    09-22 14:18:35.595 21215-26454/? D/OkHttp: --> GET http://uc1.umotional.net/urbancyclers-api/v4/directions/-2 http/1.1
    09-22 14:18:35.714 21215-26454/? D/OkHttp: <-- 200 OK http://uc1.umotional.net/urbancyclers-api/v4/directions/-2 (118ms, unknown-length body)
    09-22 14:18:35.719 800-822/? I/ActivityManager: Displayed com.umotional.bikeapp/.ui.ride.RideActivity: +461ms (total +1s327ms)
    09-22 14:18:37.658 17447-26503/? W/InvalidationClientCore: [TiclService] Ticl being stopped: Client: <ApplicationClientIdP: client_type=1018 client_name=6d43546f-a9a6-4721-8bd2-5f40bff88704>, \n\006\n\004\010\003\020\001\022\022\t\214\026\306 \350\013\020\270\021\345D\314+\2543\2413\032\007\010\2272\020\003\030\001, <RunState: 2>
    09-22 14:18:37.671 17447-26503/? W/TiclService: [TiclService] Dropping client downcall since no Ticl: <ClientDowncall: version=<Version: major_version=1 minor_version=0> ack=<AckDowncall: ack_handle=\nT\n\r\010\354\007\022\010BOOKMARK\020\001\030\360\333\276\311\356\270\326\002\"6W:Chcz6ScyivENthQQCdgIRH0DVLPPYpvqFRD7+brUvtq/rtMBGDM=0\001>>
    09-22 14:18:37.682 17447-26503/? W/TiclService: [TiclService] Dropping client downcall since no Ticl: <ClientDowncall: version=<Version: major_version=1 minor_version=0> ack=<AckDowncall: ack_handle=\nT\n\r\010\354\007\022\010PASSWORD\020\001\030\330\251\355\354\326\270\326\002\"6W:Chcz6ScyivENthQQCdgIRH0DVNNRUJXqFRD7+brUvtq/rtMBGDM=0\000>>
    09-22 14:18:37.693 17447-26507/? W/cr_invalidation: Invalidation client error:ErrorInfo: 0, false, Client does not exist on downcall, null
    09-22 14:18:37.695 17447-26503/? W/TiclService: [TiclService] Dropping client downcall since no Ticl: <ClientDowncall: version=<Version: major_version=1 minor_version=0> ack=<AckDowncall: ack_handle=\nU\n\016\010\354\007\022\tTYPED_URL\020\001\030\350\276\247\244\352\270\326\002\"6W:Chcz6ScyivENthQQCdgIRH0DVGOlSprqFRD7+brUvtq/rtMBGDM=0\001>>
    09-22 14:18:37.701 17447-26507/? W/cr_invalidation: Invalidation client error:ErrorInfo: 0, false, Client does not exist on downcall, null
    09-22 14:18:37.709 17447-26503/? W/TiclService: [TiclService] Dropping client downcall since no Ticl: <ClientDowncall: version=<Version: major_version=1 minor_version=0> ack=<AckDowncall: ack_handle=\nT\n\r\010\354\007\022\010AUTOFILL\020\001\030\330\232\303\235\276\270\326\002\"6W:Chcz6ScyivENthQQCdgIRH0DVFPMAY/qFRD7+brUvtq/rtMBGDM=0\001>>
    09-22 14:18:37.711 17447-26507/? W/cr_invalidation: Invalidation client error:ErrorInfo: 0, false, Client does not exist on downcall, null
    09-22 14:18:37.721 17447-26507/? W/cr_invalidation: Invalidation client error:ErrorInfo: 0, false, Client does not exist on downcall, null
    09-22 14:18:37.764 26487-26508/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
    09-22 14:18:37.876 26487-26487/? I/CrashlyticsCore: Initializing Crashlytics 2.3.13.145
    09-22 14:18:37.892 26487-26487/? A/Adjust: PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
    09-22 14:18:37.905 26487-26545/? W/Adjust: Missing permission: ACCESS_WIFI_STATE
    09-22 14:18:38.024 26487-26487/? D/PilgrimSdk: PilgrimSdk initialized
    09-22 14:18:38.031 26487-26557/? D/JOBS: [priority_mq] looking for next message at time 1506086318030426094
    09-22 14:18:38.031 26487-26557/? D/JOBS: flushing messages at time 1506086318030426094
    09-22 14:18:38.031 26487-26557/? D/JOBS: [priority_mq] next delayed job null
    09-22 14:18:38.032 26487-26556/? D/JOBS: [queue_CONSTRAINT_CHANGE_2] post message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@45b8ac6
    09-22 14:18:38.032 26487-26557/? D/JOBS: Job queue idle. next job at: null
    09-22 14:18:38.032 26487-26557/? D/JOBS: [priority_mq] did on idle post a message? true
    09-22 14:18:38.033 26487-26557/? D/JOBS: [priority_mq] looking for next message at time 1506086318032277083
    09-22 14:18:38.033 26487-26557/? D/JOBS: flushing messages at time 1506086318032277083
    09-22 14:18:38.033 26487-26557/? D/JOBS: [priority_mq] next delayed job null
    09-22 14:18:38.033 26487-26557/? D/JOBS: [queue_CONSTRAINT_CHANGE_2] remove message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@45b8ac6
    09-22 14:18:38.033 26487-26557/? D/JOBS: [priority_mq] consuming message of type CONSTRAINT_CHANGE
    09-22 14:18:38.033 26487-26557/? D/JOBS: considering adding a new consumer. Should poke all waiting? true isRunning? true waiting workers? 0
    09-22 14:18:38.035 26487-26557/? D/JOBS: check above load factor: totalCons:0 minCons:1 maxConsCount: 3, loadFactor 3 remainingJobs: 0 running holders: 0. isAbove:false
    09-22 14:18:38.036 26487-26557/? D/JOBS: nothing has been poked. are we above load factor? false
    09-22 14:18:38.037 26487-26557/? D/JOBS: [priority_mq] looking for next message at time 1506086318036323282
    09-22 14:18:38.037 26487-26557/? D/JOBS: flushing messages at time 1506086318036323282
    09-22 14:18:38.037 26487-26557/? D/JOBS: [priority_mq] next delayed job null
    09-22 14:18:38.037 26487-26557/? D/JOBS: [queue_CONSTRAINT_CHANGE_2] remove message null
    09-22 14:18:38.039 26487-26557/? D/JOBS: Job queue idle. next job at: null
    09-22 14:18:38.039 26487-26557/? D/JOBS: [priority_mq] did on idle post a message? false
    09-22 14:18:38.208 4442-17871/? I/GCoreUlr: Successfully inserted 1 locations

**Comment by vosecek** [comment]
I will contact authors of the app ASAP. 

Thanks for the progress.

**Comment by dpa99c** [comment]
Closed due to specified URL scheme not working and no response from the UrbanCyclers developers when contacted regarding this issue.
